"""phase4_step6_job_deduplication

Revision ID: 136fe4467b04
Revises: 9eb4e9ec37bb
Create Date: 2026-10-04 13:55:04.616278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136fe4467b04'
down_revision: Union[str, Sequence[str], None] = '9eb4e9ec37bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_duplicates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_job_id', sa.String(length=36), nullable=False),
    sa.Column('duplicate_job_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('match_method', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_job_id', 'duplicate_job_id', name='uq_canonical_duplicate')
    )
    op.create_index(op.f('ix_job_duplicates_canonical_job_id'), 'job_duplicates', ['canonical_job_id'], unique=False)
    op.create_index(op.f('ix_job_duplicates_confidence'), 'job_duplicates', ['confidence'], unique=False)
    op.create_index(op.f('ix_job_duplicates_duplicate_job_id'), 'job_duplicates', ['duplicate_job_id'], unique=False)
    op.create_index(op.f('ix_job_duplicates_status'), 'job_duplicates', ['status'], unique=False)
    op.add_column('jobs', sa.Column('canonical_job_id', sa.String(length=36), nullable=True))
    op.add_column('jobs', sa.Column('is_canonical', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('jobs', sa.Column('duplicate_status', sa.String(length=50), nullable=False, server_default=sa.text("'canonical'")))
    op.add_column('jobs', sa.Column('duplicate_confidence', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('canonical_url', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_jobs_canonical_job_id'), 'jobs', ['canonical_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_canonical_url'), 'jobs', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_jobs_duplicate_status'), 'jobs', ['duplicate_status'], unique=False)
    op.create_index(op.f('ix_jobs_is_canonical'), 'jobs', ['is_canonical'], unique=False)
    op.create_foreign_key('fk_jobs_canonical_job_id_jobs', 'jobs', 'jobs', ['canonical_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_canonical_job_id_jobs', 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_is_canonical'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_duplicate_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_canonical_url'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_canonical_job_id'), table_name='jobs')
    op.drop_column('jobs', 'canonical_url')
    op.drop_column('jobs', 'duplicate_confidence')
    op.drop_column('jobs', 'duplicate_status')
    op.drop_column('jobs', 'is_canonical')
    op.drop_column('jobs', 'canonical_job_id')
    op.drop_index(op.f('ix_job_duplicates_status'), table_name='job_duplicates')
    op.drop_index(op.f('ix_job_duplicates_duplicate_job_id'), table_name='job_duplicates')
    op.drop_index(op.f('ix_job_duplicates_confidence'), table_name='job_duplicates')
    op.drop_index(op.f('ix_job_duplicates_canonical_job_id'), table_name='job_duplicates')
    op.drop_table('job_duplicates')
    # ### end Alembic commands ###
