"""phase4_1_hard_requirement_fields

Revision ID: 219606df0d2a
Revises: a177468edbf8
Create Date: 2026-10-04 13:00:39.387230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219606df0d2a'
down_revision: Union[str, Sequence[str], None] = 'a177468edbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_results', sa.Column('has_hard_mismatch', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('match_results', sa.Column('hard_requirement_status', sa.String(length=50), nullable=False, server_default=sa.text("'PASSED'")))
    op.add_column('match_results', sa.Column('hard_requirement_warnings', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.create_index(op.f('ix_match_results_has_hard_mismatch'), 'match_results', ['has_hard_mismatch'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_results_has_hard_mismatch'), table_name='match_results')
    op.drop_column('match_results', 'hard_requirement_warnings')
    op.drop_column('match_results', 'hard_requirement_status')
    op.drop_column('match_results', 'has_hard_mismatch')
    # ### end Alembic commands ###
