"""phase4_step8_application_preparation

Revision ID: 23474b538e99
Revises: 6a9ecd24b208
Create Date: 2026-10-04 19:06:14.050695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23474b538e99'
down_revision: Union[str, Sequence[str], None] = '6a9ecd24b208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_preparations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('readiness_status', sa.String(length=50), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('readiness_reasons', sa.JSON(), nullable=True),
    sa.Column('job_snapshot', sa.JSON(), nullable=True),
    sa.Column('decision_snapshot', sa.JSON(), nullable=True),
    sa.Column('resume_recommendation', sa.JSON(), nullable=True),
    sa.Column('extracted_requirements', sa.JSON(), nullable=True),
    sa.Column('evidence_mapping', sa.JSON(), nullable=True),
    sa.Column('skills_recommendation', sa.JSON(), nullable=True),
    sa.Column('generated_content', sa.JSON(), nullable=True),
    sa.Column('question_answers', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('human_confirmation_required', sa.JSON(), nullable=True),
    sa.Column('user_overrides', sa.JSON(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_preparation_job_candidate')
    )
    op.create_index(op.f('ix_application_preparations_application_id'), 'application_preparations', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_preparations_candidate_id'), 'application_preparations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_application_preparations_engine_version'), 'application_preparations', ['engine_version'], unique=False)
    op.create_index(op.f('ix_application_preparations_job_id'), 'application_preparations', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_preparations_readiness_status'), 'application_preparations', ['readiness_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_preparations_readiness_status'), table_name='application_preparations')
    op.drop_index(op.f('ix_application_preparations_job_id'), table_name='application_preparations')
    op.drop_index(op.f('ix_application_preparations_engine_version'), table_name='application_preparations')
    op.drop_index(op.f('ix_application_preparations_candidate_id'), table_name='application_preparations')
    op.drop_index(op.f('ix_application_preparations_application_id'), table_name='application_preparations')
    op.drop_table('application_preparations')
    # ### end Alembic commands ###
