"""phase4_step9_application_execution

Revision ID: 39361debda5a
Revises: 23474b538e99
Create Date: 2026-10-04 19:32:38.909372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39361debda5a'
down_revision: Union[str, Sequence[str], None] = '23474b538e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('preparation_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('step_details', sa.JSON(), nullable=True),
    sa.Column('field_mappings', sa.JSON(), nullable=True),
    sa.Column('blocker_reason', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('requires_user_action', sa.Boolean(), nullable=False),
    sa.Column('user_action_prompt', sa.Text(), nullable=True),
    sa.Column('submission_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_evidence', sa.JSON(), nullable=True),
    sa.Column('browser_metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preparation_id'], ['application_preparations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_executions_application_id'), 'application_executions', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_executions_attempt_number'), 'application_executions', ['attempt_number'], unique=False)
    op.create_index(op.f('ix_application_executions_candidate_id'), 'application_executions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_application_executions_job_id'), 'application_executions', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_executions_mode'), 'application_executions', ['mode'], unique=False)
    op.create_index(op.f('ix_application_executions_preparation_id'), 'application_executions', ['preparation_id'], unique=False)
    op.create_index(op.f('ix_application_executions_requires_user_action'), 'application_executions', ['requires_user_action'], unique=False)
    op.create_index(op.f('ix_application_executions_source'), 'application_executions', ['source'], unique=False)
    op.create_index(op.f('ix_application_executions_status'), 'application_executions', ['status'], unique=False)
    op.create_index(op.f('ix_application_executions_submission_confirmed'), 'application_executions', ['submission_confirmed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_executions_submission_confirmed'), table_name='application_executions')
    op.drop_index(op.f('ix_application_executions_status'), table_name='application_executions')
    op.drop_index(op.f('ix_application_executions_source'), table_name='application_executions')
    op.drop_index(op.f('ix_application_executions_requires_user_action'), table_name='application_executions')
    op.drop_index(op.f('ix_application_executions_preparation_id'), table_name='application_executions')
    op.drop_index(op.f('ix_application_executions_mode'), table_name='application_executions')
    op.drop_index(op.f('ix_application_executions_job_id'), table_name='application_executions')
    op.drop_index(op.f('ix_application_executions_candidate_id'), table_name='application_executions')
    op.drop_index(op.f('ix_application_executions_attempt_number'), table_name='application_executions')
    op.drop_index(op.f('ix_application_executions_application_id'), table_name='application_executions')
    op.drop_table('application_executions')
    # ### end Alembic commands ###
