"""phase4_step10_application_memory

Revision ID: 5f98945421f0
Revises: 39361debda5a
Create Date: 2026-10-04 20:12:59.261000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f98945421f0'
down_revision: Union[str, Sequence[str], None] = '39361debda5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_notes_application_id'), 'application_notes', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_notes_category'), 'application_notes', ['category'], unique=False)
    op.create_table('application_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('original_decision', sa.String(length=50), nullable=False),
    sa.Column('override_decision', sa.String(length=50), nullable=False),
    sa.Column('override_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_overrides_application_id'), 'application_overrides', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_overrides_original_decision'), 'application_overrides', ['original_decision'], unique=False)
    op.create_index(op.f('ix_application_overrides_override_decision'), 'application_overrides', ['override_decision'], unique=False)
    op.add_column('application_events', sa.Column('actor', sa.String(length=50), nullable=False, server_default='system'))
    op.add_column('application_events', sa.Column('provenance', sa.String(length=50), nullable=False, server_default='SYSTEM_DETECTED'))
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    op.add_column('applications', sa.Column('lifecycle_stage', sa.String(length=50), nullable=False, server_default='NOT_STARTED'))
    op.add_column('applications', sa.Column('outcome_category', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('outcome_provenance', sa.String(length=50), nullable=False, server_default='UNKNOWN'))
    op.add_column('applications', sa.Column('rejection_category', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('last_outcome_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('candidate_snapshot', sa.JSON(), nullable=True))
    op.add_column('applications', sa.Column('job_snapshot', sa.JSON(), nullable=True))
    op.add_column('applications', sa.Column('decision_snapshot', sa.JSON(), nullable=True))
    op.add_column('applications', sa.Column('artifacts_snapshot', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_applications_lifecycle_stage'), 'applications', ['lifecycle_stage'], unique=False)
    op.create_index(op.f('ix_applications_outcome_category'), 'applications', ['outcome_category'], unique=False)
    op.create_index(op.f('ix_applications_outcome_provenance'), 'applications', ['outcome_provenance'], unique=False)
    op.create_index(op.f('ix_applications_rejection_category'), 'applications', ['rejection_category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_rejection_category'), table_name='applications')
    op.drop_index(op.f('ix_applications_outcome_provenance'), table_name='applications')
    op.drop_index(op.f('ix_applications_outcome_category'), table_name='applications')
    op.drop_index(op.f('ix_applications_lifecycle_stage'), table_name='applications')
    op.drop_column('applications', 'artifacts_snapshot')
    op.drop_column('applications', 'decision_snapshot')
    op.drop_column('applications', 'job_snapshot')
    op.drop_column('applications', 'candidate_snapshot')
    op.drop_column('applications', 'last_outcome_date')
    op.drop_column('applications', 'rejection_reason')
    op.drop_column('applications', 'rejection_category')
    op.drop_column('applications', 'outcome_provenance')
    op.drop_column('applications', 'outcome_category')
    op.drop_column('applications', 'lifecycle_stage')
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_column('application_events', 'provenance')
    op.drop_column('application_events', 'actor')
    op.drop_index(op.f('ix_application_overrides_override_decision'), table_name='application_overrides')
    op.drop_index(op.f('ix_application_overrides_original_decision'), table_name='application_overrides')
    op.drop_index(op.f('ix_application_overrides_application_id'), table_name='application_overrides')
    op.drop_table('application_overrides')
    op.drop_index(op.f('ix_application_notes_category'), table_name='application_notes')
    op.drop_index(op.f('ix_application_notes_application_id'), table_name='application_notes')
    op.drop_table('application_notes')
    # ### end Alembic commands ###
