"""add_uq_source_external_job_id

Revision ID: 96fc4e88a575
Revises: 51289f6bb788
Create Date: 2026-10-03 13:57:47.751010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fc4e88a575'
down_revision: Union[str, Sequence[str], None] = '51289f6bb788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_source_external_job_id', 'jobs', ['source', 'external_job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_source_external_job_id', 'jobs', type_='unique')
    # ### end Alembic commands ###
