"""phase3_job_ingestion_fields

Revision ID: 98aeb200d6ab
Revises: cb6f09773388
Create Date: 2026-10-03 18:39:47.545855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98aeb200d6ab'
down_revision: Union[str, Sequence[str], None] = 'cb6f09773388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('responsibilities', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('raw_payload', sa.Text(), nullable=True))
    op.add_column('search_queries', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('search_queries', sa.Column('parameters', sa.Text(), nullable=True))
    op.add_column('search_queries', sa.Column('result_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('source_statuses', sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('source_statuses', sa.Column('jobs_fetched', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('source_statuses', sa.Column('jobs_created', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('source_statuses', sa.Column('jobs_updated', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_statuses', 'jobs_updated')
    op.drop_column('source_statuses', 'jobs_created')
    op.drop_column('source_statuses', 'jobs_fetched')
    op.drop_column('source_statuses', 'last_failure_at')
    op.drop_column('search_queries', 'result_count')
    op.drop_column('search_queries', 'parameters')
    op.drop_column('search_queries', 'location')
    op.drop_column('jobs', 'raw_payload')
    op.drop_column('jobs', 'last_seen_at')
    op.drop_column('jobs', 'expires_at')
    op.drop_column('jobs', 'responsibilities')
    op.drop_column('jobs', 'requirements')
    # ### end Alembic commands ###
