"""phase2_profile_system

Revision ID: 9d6f4c9190c6
Revises: 96fc4e88a575
Create Date: 2026-10-03 17:06:12.331874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6f4c9190c6'
down_revision: Union[str, Sequence[str], None] = '96fc4e88a575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('role_priority', sa.JSON(), nullable=False),
    sa.Column('preferred_locations', sa.JSON(), nullable=False),
    sa.Column('location_priority', sa.JSON(), nullable=False),
    sa.Column('work_modes', sa.JSON(), nullable=False),
    sa.Column('minimum_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('experience_preference', sa.String(length=50), nullable=False),
    sa.Column('employment_types', sa.JSON(), nullable=False),
    sa.Column('relocation_allowed', sa.Boolean(), nullable=False),
    sa.Column('startup_allowed', sa.Boolean(), nullable=False),
    sa.Column('service_company_allowed', sa.Boolean(), nullable=False),
    sa.Column('product_company_allowed', sa.Boolean(), nullable=False),
    sa.Column('internship_allowed', sa.Boolean(), nullable=False),
    sa.Column('contract_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.String(length=50), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('credential_url', sa.String(length=1000), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('document_ref', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.add_column('educations', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('educations', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('educations', sa.Column('status', sa.String(length=50), server_default='CONFIRMED', nullable=False))
    op.add_column('experiences', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('experiences', sa.Column('employment_type', sa.String(length=100), nullable=True))
    op.add_column('experiences', sa.Column('responsibilities', sa.JSON(), nullable=True))
    op.add_column('experiences', sa.Column('achievements', sa.JSON(), nullable=True))
    op.add_column('experiences', sa.Column('technologies', sa.String(length=500), nullable=True))
    op.add_column('experiences', sa.Column('status', sa.String(length=50), server_default='CONFIRMED', nullable=False))
    op.add_column('projects', sa.Column('role', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('repo_url', sa.String(length=1000), nullable=True))
    op.add_column('projects', sa.Column('demo_url', sa.String(length=1000), nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(length=50), server_default='CONFIRMED', nullable=False))
    op.add_column('skills', sa.Column('proficiency', sa.String(length=50), nullable=True))
    op.add_column('skills', sa.Column('status', sa.String(length=50), server_default='CONFIRMED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'status')
    op.drop_column('skills', 'proficiency')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'demo_url')
    op.drop_column('projects', 'repo_url')
    op.drop_column('projects', 'role')
    op.drop_column('experiences', 'status')
    op.drop_column('experiences', 'technologies')
    op.drop_column('experiences', 'achievements')
    op.drop_column('experiences', 'responsibilities')
    op.drop_column('experiences', 'employment_type')
    op.drop_column('experiences', 'location')
    op.drop_column('educations', 'status')
    op.drop_column('educations', 'details')
    op.drop_column('educations', 'location')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'source')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    op.drop_table('certifications')
    op.drop_table('candidate_preferences')
    # ### end Alembic commands ###
