"""phase4_step4_discovery_runs

Revision ID: 9eb4e9ec37bb
Revises: 219606df0d2a
Create Date: 2026-10-04 13:40:41.131824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb4e9ec37bb'
down_revision: Union[str, Sequence[str], None] = '219606df0d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('queries_generated', sa.Integer(), nullable=False),
    sa.Column('queries_executed', sa.Integer(), nullable=False),
    sa.Column('successful_queries', sa.Integer(), nullable=False),
    sa.Column('failed_queries', sa.Integer(), nullable=False),
    sa.Column('jobs_fetched', sa.Integer(), nullable=False),
    sa.Column('jobs_created', sa.Integer(), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), nullable=False),
    sa.Column('jobs_skipped', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_runs_candidate_id'), 'discovery_runs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_discovery_runs_source'), 'discovery_runs', ['source'], unique=False)
    op.create_index(op.f('ix_discovery_runs_status'), 'discovery_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovery_runs_status'), table_name='discovery_runs')
    op.drop_index(op.f('ix_discovery_runs_source'), table_name='discovery_runs')
    op.drop_index(op.f('ix_discovery_runs_candidate_id'), table_name='discovery_runs')
    op.drop_table('discovery_runs')
    # ### end Alembic commands ###
