"""government_hierarchy_and_unresolved_backlog

Revision ID: c89beed3dd77
Revises: da88676817e6
Create Date: 2026-10-05 23:15:07.637785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89beed3dd77'
down_revision: Union[str, Sequence[str], None] = 'da88676817e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_unresolved_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('attempted_queries', sa.Text(), nullable=True),
    sa.Column('attempted_domains', sa.Text(), nullable=True),
    sa.Column('discovery_status', sa.String(length=50), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_source_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_source_id'], ['government_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_unresolved_targets_discovery_status'), 'government_unresolved_targets', ['discovery_status'], unique=False)
    op.create_index(op.f('ix_government_unresolved_targets_district'), 'government_unresolved_targets', ['district'], unique=False)
    op.create_index(op.f('ix_government_unresolved_targets_resolved_source_id'), 'government_unresolved_targets', ['resolved_source_id'], unique=False)
    op.create_index(op.f('ix_government_unresolved_targets_retry_at'), 'government_unresolved_targets', ['retry_at'], unique=False)
    op.create_index(op.f('ix_government_unresolved_targets_state'), 'government_unresolved_targets', ['state'], unique=False)
    op.create_index(op.f('ix_government_unresolved_targets_target_name'), 'government_unresolved_targets', ['target_name'], unique=False)
    op.create_index(op.f('ix_government_unresolved_targets_target_type'), 'government_unresolved_targets', ['target_type'], unique=False)
    op.add_column('government_sources', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('government_sources', sa.Column('parent_source_id', sa.String(length=36), nullable=True))
    op.add_column('government_sources', sa.Column('confidence_category', sa.String(length=50), nullable=False, server_default='AUTHORITATIVE'))
    op.create_index(op.f('ix_government_sources_confidence_category'), 'government_sources', ['confidence_category'], unique=False)
    op.create_index(op.f('ix_government_sources_district'), 'government_sources', ['district'], unique=False)
    op.create_index(op.f('ix_government_sources_parent_source_id'), 'government_sources', ['parent_source_id'], unique=False)
    op.create_foreign_key('fk_government_sources_parent_source_id', 'government_sources', 'government_sources', ['parent_source_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_government_sources_parent_source_id', 'government_sources', type_='foreignkey')
    op.drop_index(op.f('ix_government_sources_parent_source_id'), table_name='government_sources')
    op.drop_index(op.f('ix_government_sources_district'), table_name='government_sources')
    op.drop_index(op.f('ix_government_sources_confidence_category'), table_name='government_sources')
    op.drop_column('government_sources', 'confidence_category')
    op.drop_column('government_sources', 'parent_source_id')
    op.drop_column('government_sources', 'district')
    op.drop_index(op.f('ix_government_unresolved_targets_target_type'), table_name='government_unresolved_targets')
    op.drop_index(op.f('ix_government_unresolved_targets_target_name'), table_name='government_unresolved_targets')
    op.drop_index(op.f('ix_government_unresolved_targets_state'), table_name='government_unresolved_targets')
    op.drop_index(op.f('ix_government_unresolved_targets_retry_at'), table_name='government_unresolved_targets')
    op.drop_index(op.f('ix_government_unresolved_targets_resolved_source_id'), table_name='government_unresolved_targets')
    op.drop_index(op.f('ix_government_unresolved_targets_district'), table_name='government_unresolved_targets')
    op.drop_index(op.f('ix_government_unresolved_targets_discovery_status'), table_name='government_unresolved_targets')
    op.drop_table('government_unresolved_targets')
    # ### end Alembic commands ###
