"""add_salary_status_to_candidate_preferences

Revision ID: cb6f09773388
Revises: 9d6f4c9190c6
Create Date: 2026-10-03 18:12:51.955923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6f09773388'
down_revision: Union[str, Sequence[str], None] = '9d6f4c9190c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_preferences', sa.Column('salary_status', sa.String(length=50), server_default='NEEDS_CONFIRMATION', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_preferences', 'salary_status')
    # ### end Alembic commands ###
