"""government_job_source_discovery

Revision ID: d47021df7af4
Revises: f4d435e5ab97
Create Date: 2026-10-05 19:12:15.597112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47021df7af4'
down_revision: Union[str, Sequence[str], None] = 'f4d435e5ab97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_discovery_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scope_filter', sa.String(length=100), nullable=True),
    sa.Column('sources_discovered', sa.Integer(), nullable=False),
    sa.Column('sources_verified', sa.Integer(), nullable=False),
    sa.Column('vacancies_discovered', sa.Integer(), nullable=False),
    sa.Column('vacancies_created', sa.Integer(), nullable=False),
    sa.Column('vacancies_updated', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coverage_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_discovery_runs_status'), 'government_discovery_runs', ['status'], unique=False)
    op.create_table('government_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_name', sa.String(length=255), nullable=False),
    sa.Column('organisation_type', sa.String(length=100), nullable=False),
    sa.Column('government_level', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('official_domain', sa.String(length=255), nullable=False),
    sa.Column('career_url', sa.String(length=1000), nullable=True),
    sa.Column('recruitment_url', sa.String(length=1000), nullable=True),
    sa.Column('vacancy_url', sa.String(length=1000), nullable=True),
    sa.Column('notification_url', sa.String(length=1000), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_status', sa.String(length=50), nullable=False),
    sa.Column('discovery_method', sa.String(length=100), nullable=False),
    sa.Column('discovered_from', sa.String(length=1000), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawl_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('crawl_status', sa.String(length=50), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('vacancies_found', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_sources_government_level'), 'government_sources', ['government_level'], unique=False)
    op.create_index(op.f('ix_government_sources_official_domain'), 'government_sources', ['official_domain'], unique=True)
    op.create_index(op.f('ix_government_sources_organisation_name'), 'government_sources', ['organisation_name'], unique=False)
    op.create_index(op.f('ix_government_sources_organisation_type'), 'government_sources', ['organisation_type'], unique=False)
    op.create_index(op.f('ix_government_sources_source_status'), 'government_sources', ['source_status'], unique=False)
    op.create_index(op.f('ix_government_sources_source_type'), 'government_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_government_sources_state'), 'government_sources', ['state'], unique=False)
    op.create_table('government_vacancies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('government_level', sa.String(length=50), nullable=False),
    sa.Column('organisation_type', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('ministry', sa.String(length=255), nullable=True),
    sa.Column('scheme_or_project', sa.String(length=255), nullable=True),
    sa.Column('advertisement_number', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('contract_duration', sa.String(length=100), nullable=True),
    sa.Column('pay_scale', sa.String(length=255), nullable=True),
    sa.Column('number_of_positions', sa.Integer(), nullable=True),
    sa.Column('age_limit', sa.String(length=100), nullable=True),
    sa.Column('selection_process', sa.String(length=255), nullable=True),
    sa.Column('official_notification_url', sa.String(length=1000), nullable=True),
    sa.Column('official_application_url', sa.String(length=1000), nullable=True),
    sa.Column('application_mode', sa.String(length=50), nullable=False),
    sa.Column('application_email', sa.String(length=255), nullable=True),
    sa.Column('document_requirements', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('pdf_extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=50), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('corrigendum_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['government_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_vacancies_advertisement_number'), 'government_vacancies', ['advertisement_number'], unique=False)
    op.create_index(op.f('ix_government_vacancies_employment_type'), 'government_vacancies', ['employment_type'], unique=False)
    op.create_index(op.f('ix_government_vacancies_government_level'), 'government_vacancies', ['government_level'], unique=False)
    op.create_index(op.f('ix_government_vacancies_job_id'), 'government_vacancies', ['job_id'], unique=True)
    op.create_index(op.f('ix_government_vacancies_organisation_type'), 'government_vacancies', ['organisation_type'], unique=False)
    op.create_index(op.f('ix_government_vacancies_pdf_sha256'), 'government_vacancies', ['pdf_sha256'], unique=False)
    op.create_index(op.f('ix_government_vacancies_source_id'), 'government_vacancies', ['source_id'], unique=False)
    op.create_index(op.f('ix_government_vacancies_state'), 'government_vacancies', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_government_vacancies_state'), table_name='government_vacancies')
    op.drop_index(op.f('ix_government_vacancies_source_id'), table_name='government_vacancies')
    op.drop_index(op.f('ix_government_vacancies_pdf_sha256'), table_name='government_vacancies')
    op.drop_index(op.f('ix_government_vacancies_organisation_type'), table_name='government_vacancies')
    op.drop_index(op.f('ix_government_vacancies_job_id'), table_name='government_vacancies')
    op.drop_index(op.f('ix_government_vacancies_government_level'), table_name='government_vacancies')
    op.drop_index(op.f('ix_government_vacancies_employment_type'), table_name='government_vacancies')
    op.drop_index(op.f('ix_government_vacancies_advertisement_number'), table_name='government_vacancies')
    op.drop_table('government_vacancies')
    op.drop_index(op.f('ix_government_sources_state'), table_name='government_sources')
    op.drop_index(op.f('ix_government_sources_source_type'), table_name='government_sources')
    op.drop_index(op.f('ix_government_sources_source_status'), table_name='government_sources')
    op.drop_index(op.f('ix_government_sources_organisation_type'), table_name='government_sources')
    op.drop_index(op.f('ix_government_sources_organisation_name'), table_name='government_sources')
    op.drop_index(op.f('ix_government_sources_official_domain'), table_name='government_sources')
    op.drop_index(op.f('ix_government_sources_government_level'), table_name='government_sources')
    op.drop_table('government_sources')
    op.drop_index(op.f('ix_government_discovery_runs_status'), table_name='government_discovery_runs')
    op.drop_table('government_discovery_runs')
    # ### end Alembic commands ###
