"""government_monitoring_and_freshness

Revision ID: da88676817e6
Revises: d47021df7af4
Create Date: 2026-10-05 21:50:49.184146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da88676817e6'
down_revision: Union[str, Sequence[str], None] = 'd47021df7af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_change_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('vacancy_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('new_hash', sa.String(length=64), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['government_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['government_vacancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_change_events_change_type'), 'government_change_events', ['change_type'], unique=False)
    op.create_index(op.f('ix_government_change_events_detected_at'), 'government_change_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_government_change_events_source_id'), 'government_change_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_government_change_events_vacancy_id'), 'government_change_events', ['vacancy_id'], unique=False)
    op.add_column('government_sources', sa.Column('crawl_interval_minutes', sa.Integer(), nullable=False, server_default=sa.text('1440')))
    op.add_column('government_sources', sa.Column('next_crawl_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('government_sources', sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('government_sources', sa.Column('last_successful_crawl_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('government_sources', sa.Column('last_change_detected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('government_sources', sa.Column('crawl_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('government_sources', sa.Column('successful_crawl_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('government_sources', sa.Column('failed_crawl_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('government_sources', sa.Column('consecutive_failures', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('government_sources', sa.Column('change_frequency_category', sa.String(length=50), nullable=False, server_default=sa.text("'low'")))
    op.add_column('government_sources', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('government_sources', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_government_sources_change_frequency_category'), 'government_sources', ['change_frequency_category'], unique=False)
    op.create_index(op.f('ix_government_sources_next_crawl_at'), 'government_sources', ['next_crawl_at'], unique=False)
    op.add_column('government_vacancies', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('government_vacancies', sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('government_vacancies', sa.Column('deadline_status', sa.String(length=50), nullable=False, server_default=sa.text("'UNKNOWN'")))
    op.add_column('government_vacancies', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_government_vacancies_application_deadline'), 'government_vacancies', ['application_deadline'], unique=False)
    op.create_index(op.f('ix_government_vacancies_deadline_status'), 'government_vacancies', ['deadline_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_government_vacancies_deadline_status'), table_name='government_vacancies')
    op.drop_index(op.f('ix_government_vacancies_application_deadline'), table_name='government_vacancies')
    op.drop_column('government_vacancies', 'last_verified_at')
    op.drop_column('government_vacancies', 'deadline_status')
    op.drop_column('government_vacancies', 'application_deadline')
    op.drop_column('government_vacancies', 'published_at')
    op.drop_index(op.f('ix_government_sources_next_crawl_at'), table_name='government_sources')
    op.drop_index(op.f('ix_government_sources_change_frequency_category'), table_name='government_sources')
    op.drop_column('government_sources', 'locked_at')
    op.drop_column('government_sources', 'is_locked')
    op.drop_column('government_sources', 'change_frequency_category')
    op.drop_column('government_sources', 'consecutive_failures')
    op.drop_column('government_sources', 'failed_crawl_count')
    op.drop_column('government_sources', 'successful_crawl_count')
    op.drop_column('government_sources', 'crawl_count')
    op.drop_column('government_sources', 'last_change_detected_at')
    op.drop_column('government_sources', 'last_successful_crawl_at')
    op.drop_column('government_sources', 'last_crawled_at')
    op.drop_column('government_sources', 'next_crawl_at')
    op.drop_column('government_sources', 'crawl_interval_minutes')
    op.drop_index(op.f('ix_government_change_events_vacancy_id'), table_name='government_change_events')
    op.drop_index(op.f('ix_government_change_events_source_id'), table_name='government_change_events')
    op.drop_index(op.f('ix_government_change_events_detected_at'), table_name='government_change_events')
    op.drop_index(op.f('ix_government_change_events_change_type'), table_name='government_change_events')
    op.drop_table('government_change_events')
    # ### end Alembic commands ###
