"""phase4_step12_controlled_autonomy

Revision ID: f4d435e5ab97
Revises: 5f98945421f0
Create Date: 2026-10-04 21:08:21.520554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d435e5ab97'
down_revision: Union[str, Sequence[str], None] = '5f98945421f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('job_discovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('matching_enabled', sa.Boolean(), nullable=False),
    sa.Column('deduplication_enabled', sa.Boolean(), nullable=False),
    sa.Column('preparation_enabled', sa.Boolean(), nullable=False),
    sa.Column('submission_requires_approval', sa.Boolean(), nullable=False),
    sa.Column('discovery_interval_hours', sa.Integer(), nullable=False),
    sa.Column('max_daily_preparations', sa.Integer(), nullable=False),
    sa.Column('stale_job_threshold_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_settings_candidate_id'), 'automation_settings', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_automation_settings_mode'), 'automation_settings', ['mode'], unique=False)
    op.create_table('automation_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_automation_task_idempotency_key')
    )
    op.create_index(op.f('ix_automation_tasks_application_id'), 'automation_tasks', ['application_id'], unique=False)
    op.create_index(op.f('ix_automation_tasks_available_at'), 'automation_tasks', ['available_at'], unique=False)
    op.create_index(op.f('ix_automation_tasks_candidate_id'), 'automation_tasks', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_automation_tasks_created_at'), 'automation_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_tasks_error_category'), 'automation_tasks', ['error_category'], unique=False)
    op.create_index(op.f('ix_automation_tasks_idempotency_key'), 'automation_tasks', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_automation_tasks_job_id'), 'automation_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_automation_tasks_locked_at'), 'automation_tasks', ['locked_at'], unique=False)
    op.create_index(op.f('ix_automation_tasks_locked_by'), 'automation_tasks', ['locked_by'], unique=False)
    op.create_index(op.f('ix_automation_tasks_priority'), 'automation_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_automation_tasks_status'), 'automation_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_automation_tasks_task_type'), 'automation_tasks', ['task_type'], unique=False)
    op.create_table('application_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('preparation_id', sa.String(length=36), nullable=True),
    sa.Column('preparation_version', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approval_scope', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preparation_id'], ['application_preparations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_approvals_application_id'), 'application_approvals', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_approvals_approval_status'), 'application_approvals', ['approval_status'], unique=False)
    op.create_index(op.f('ix_application_approvals_candidate_id'), 'application_approvals', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_application_approvals_job_id'), 'application_approvals', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_approvals_preparation_id'), 'application_approvals', ['preparation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_approvals_preparation_id'), table_name='application_approvals')
    op.drop_index(op.f('ix_application_approvals_job_id'), table_name='application_approvals')
    op.drop_index(op.f('ix_application_approvals_candidate_id'), table_name='application_approvals')
    op.drop_index(op.f('ix_application_approvals_approval_status'), table_name='application_approvals')
    op.drop_index(op.f('ix_application_approvals_application_id'), table_name='application_approvals')
    op.drop_table('application_approvals')
    op.drop_index(op.f('ix_automation_tasks_task_type'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_status'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_priority'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_locked_by'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_locked_at'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_job_id'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_idempotency_key'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_error_category'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_created_at'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_candidate_id'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_available_at'), table_name='automation_tasks')
    op.drop_index(op.f('ix_automation_tasks_application_id'), table_name='automation_tasks')
    op.drop_table('automation_tasks')
    op.drop_index(op.f('ix_automation_settings_mode'), table_name='automation_settings')
    op.drop_index(op.f('ix_automation_settings_candidate_id'), table_name='automation_settings')
    op.drop_table('automation_settings')
    # ### end Alembic commands ###
