"""
Authoritative Public Sector Domain & Hierarchy Directory.
Maintains curated, official, and verified Indian government domains, recruitment URLs,
organisational types, and parent-child administrative mappings.
"""
from typing import Dict, Any

AUTHORITATIVE_DOMAIN_DIRECTORY: Dict[str, Dict[str, Any]] = {
    # ==========================================
    # 1. NATIONAL COMMISSIONS & RECRUITMENT BOARDS
    # ==========================================
    "Union Public Service Commission (UPSC)": {
        "organisation_name": "Union Public Service Commission (UPSC)",
        "organisation_type": "statutory_body",
        "government_level": "central",
        "official_domain": "upsc.gov.in",
        "career_url": "https://upsc.gov.in/recruitment",
        "recruitment_url": "https://upsc.gov.in/recruitment/recruitment-advertisement",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Staff Selection Commission (SSC)": {
        "organisation_name": "Staff Selection Commission (SSC)",
        "organisation_type": "statutory_body",
        "government_level": "central",
        "official_domain": "ssc.gov.in",
        "career_url": "https://ssc.gov.in/candidate-portal/notices",
        "recruitment_url": "https://ssc.gov.in/candidate-portal/notices",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "National Career Service (NCS)": {
        "organisation_name": "National Career Service (NCS)",
        "organisation_type": "portal",
        "government_level": "central",
        "official_domain": "ncs.gov.in",
        "career_url": "https://www.ncs.gov.in/job-seeker/Pages/Search.aspx",
        "recruitment_url": "https://www.ncs.gov.in/job-seeker/Pages/Search.aspx",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Employment News / Rozgar Samachar": {
        "organisation_name": "Employment News / Rozgar Samachar",
        "organisation_type": "portal",
        "government_level": "central",
        "official_domain": "employmentnews.gov.in",
        "career_url": "https://employmentnews.gov.in/NewEmp/Home.aspx",
        "recruitment_url": "https://employmentnews.gov.in/NewEmp/Home.aspx",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Railway Recruitment Boards (RRB)": {
        "organisation_name": "Railway Recruitment Control Board",
        "organisation_type": "statutory_body",
        "government_level": "central",
        "official_domain": "rrbcdg.gov.in",
        "career_url": "https://www.rrbcdg.gov.in/",
        "recruitment_url": "https://www.rrbcdg.gov.in/",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "National Testing Agency (NTA)": {
        "organisation_name": "National Testing Agency (NTA)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "official_domain": "nta.ac.in",
        "career_url": "https://nta.ac.in/NoticeArchive",
        "recruitment_url": "https://nta.ac.in/NoticeArchive",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Institute of Banking Personnel Selection (IBPS)": {
        "organisation_name": "Institute of Banking Personnel Selection (IBPS)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "official_domain": "ibps.in",
        "career_url": "https://www.ibps.in/",
        "recruitment_url": "https://www.ibps.in/",
        "confidence_category": "GOVERNMENT_AFFILIATED",
        "confidence": 0.95,
    },

    # ==========================================
    # 2. CENTRAL MINISTRIES & DEPARTMENTS
    # ==========================================
    "Department of Personnel & Training (DoPT)": {
        "organisation_name": "Department of Personnel & Training (DoPT)",
        "organisation_type": "department",
        "government_level": "central",
        "official_domain": "dopt.gov.in",
        "career_url": "https://dopt.gov.in/vacancies",
        "recruitment_url": "https://dopt.gov.in/vacancies",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Ministry of Electronics & Information Technology (MeitY)": {
        "organisation_name": "Ministry of Electronics & Information Technology (MeitY)",
        "organisation_type": "ministry",
        "government_level": "central",
        "official_domain": "meity.gov.in",
        "career_url": "https://www.meity.gov.in/content/recruitment",
        "recruitment_url": "https://www.meity.gov.in/content/recruitment",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Department of Science & Technology (DST)": {
        "organisation_name": "Department of Science & Technology (DST)",
        "organisation_type": "department",
        "government_level": "central",
        "official_domain": "dst.gov.in",
        "career_url": "https://dst.gov.in/recruitment",
        "recruitment_url": "https://dst.gov.in/recruitment",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Department of Biotechnology (DBT)": {
        "organisation_name": "Department of Biotechnology (DBT)",
        "organisation_type": "department",
        "government_level": "central",
        "official_domain": "dbtindia.gov.in",
        "career_url": "https://dbtindia.gov.in/whats-new/vacancies",
        "recruitment_url": "https://dbtindia.gov.in/whats-new/vacancies",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Ministry of Labour & Employment": {
        "organisation_name": "Ministry of Labour & Employment",
        "organisation_type": "ministry",
        "government_level": "central",
        "official_domain": "labour.gov.in",
        "career_url": "https://labour.gov.in/vacancies",
        "recruitment_url": "https://labour.gov.in/vacancies",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Ministry of Finance": {
        "organisation_name": "Ministry of Finance",
        "organisation_type": "ministry",
        "government_level": "central",
        "official_domain": "finmin.nic.in",
        "career_url": "https://finmin.nic.in/vacancies",
        "recruitment_url": "https://finmin.nic.in/vacancies",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Ministry of Education": {
        "organisation_name": "Ministry of Education",
        "organisation_type": "ministry",
        "government_level": "central",
        "official_domain": "education.gov.in",
        "career_url": "https://www.education.gov.in/vacancies",
        "recruitment_url": "https://www.education.gov.in/vacancies",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Ministry of Health & Family Welfare": {
        "organisation_name": "Ministry of Health & Family Welfare",
        "organisation_type": "ministry",
        "government_level": "central",
        "official_domain": "mohfw.gov.in",
        "career_url": "https://main.mohfw.gov.in/vacancies",
        "recruitment_url": "https://main.mohfw.gov.in/vacancies",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Ministry of Earth Sciences": {
        "organisation_name": "Ministry of Earth Sciences",
        "organisation_type": "ministry",
        "government_level": "central",
        "official_domain": "moes.gov.in",
        "career_url": "https://www.moes.gov.in/recruitment",
        "recruitment_url": "https://www.moes.gov.in/recruitment",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Department of Telecommunications (DoT)": {
        "organisation_name": "Department of Telecommunications (DoT)",
        "organisation_type": "department",
        "government_level": "central",
        "official_domain": "dot.gov.in",
        "career_url": "https://dot.gov.in/vacancies",
        "recruitment_url": "https://dot.gov.in/vacancies",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Department of Posts": {
        "organisation_name": "Department of Posts (India Post)",
        "organisation_type": "department",
        "government_level": "central",
        "official_domain": "indiapost.gov.in",
        "career_url": "https://www.indiapost.gov.in/VAS/Pages/Recruitment.aspx",
        "recruitment_url": "https://www.indiapost.gov.in/VAS/Pages/Recruitment.aspx",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Ministry of Skill Development & Entrepreneurship": {
        "organisation_name": "Ministry of Skill Development & Entrepreneurship",
        "organisation_type": "ministry",
        "government_level": "central",
        "official_domain": "msde.gov.in",
        "career_url": "https://www.msde.gov.in/en/vacancies",
        "recruitment_url": "https://www.msde.gov.in/en/vacancies",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },

    # ==========================================
    # 3. DIGITAL, IT & CYBERSECURITY ENTERPRISES
    # ==========================================
    "National Informatics Centre (NIC)": {
        "organisation_name": "National Informatics Centre (NIC)",
        "organisation_type": "attached_office",
        "government_level": "central",
        "official_domain": "nic.in",
        "career_url": "https://www.nic.in/vacancies/",
        "recruitment_url": "https://www.nic.in/vacancies/",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "National Informatics Centre Services Inc. (NICSI)": {
        "organisation_name": "National Informatics Centre Services Inc. (NICSI)",
        "organisation_type": "psu",
        "government_level": "central",
        "official_domain": "nicsi.com",
        "career_url": "https://nicsi.com/careers/",
        "recruitment_url": "https://nicsi.com/careers/",
        "parent_organisation": "National Informatics Centre (NIC)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Centre for Development of Advanced Computing (C-DAC)": {
        "organisation_name": "Centre for Development of Advanced Computing (C-DAC)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "official_domain": "cdac.in",
        "career_url": "https://www.cdac.in/index.aspx?id=careers",
        "recruitment_url": "https://www.cdac.in/index.aspx?id=current_jobs",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "National Institute of Electronics & Information Technology (NIELIT)": {
        "organisation_name": "National Institute of Electronics & Information Technology (NIELIT)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "official_domain": "nielit.gov.in",
        "career_url": "https://www.nielit.gov.in/recruitments",
        "recruitment_url": "https://www.nielit.gov.in/recruitments",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Software Technology Parks of India (STPI)": {
        "organisation_name": "Software Technology Parks of India (STPI)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "official_domain": "stpi.in",
        "career_url": "https://stpi.in/en/careers",
        "recruitment_url": "https://stpi.in/en/careers",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Digital India Corporation (DIC)": {
        "organisation_name": "Digital India Corporation (DIC)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "official_domain": "dic.gov.in",
        "career_url": "https://dic.gov.in/index.php/vacancies",
        "recruitment_url": "https://dic.gov.in/index.php/vacancies",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "National e-Governance Division (NeGD)": {
        "organisation_name": "National e-Governance Division (NeGD)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "official_domain": "negd.gov.in",
        "career_url": "https://negd.gov.in/careers/",
        "recruitment_url": "https://negd.gov.in/careers/",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Indian Computer Emergency Response Team (CERT-In)": {
        "organisation_name": "Indian Computer Emergency Response Team (CERT-In)",
        "organisation_type": "attached_office",
        "government_level": "central",
        "official_domain": "cert-in.org.in",
        "career_url": "https://www.cert-in.org.in/vacancies.jsp",
        "recruitment_url": "https://www.cert-in.org.in/vacancies.jsp",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "ERNET India": {
        "organisation_name": "ERNET India",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "official_domain": "ernet.in",
        "career_url": "https://ernet.in/vacancies",
        "recruitment_url": "https://ernet.in/vacancies",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Centre for Development of Telematics (C-DOT)": {
        "organisation_name": "Centre for Development of Telematics (C-DOT)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "official_domain": "cdot.in",
        "career_url": "https://www.cdot.in/cdotweb/web/careers.php",
        "recruitment_url": "https://www.cdot.in/cdotweb/web/careers.php",
        "parent_organisation": "Department of Telecommunications (DoT)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },

    # ==========================================
    # 4. SPACE, DEFENCE & STRATEGIC RESEARCH
    # ==========================================
    "Indian Space Research Organisation (ISRO)": {
        "organisation_name": "Indian Space Research Organisation (ISRO)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "isro.gov.in",
        "career_url": "https://www.isro.gov.in/Careers.html",
        "recruitment_url": "https://www.isro.gov.in/Careers.html",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Defence Research & Development Organisation (DRDO)": {
        "organisation_name": "Defence Research & Development Organisation (DRDO)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "drdo.gov.in",
        "career_url": "https://www.drdo.gov.in/careers",
        "recruitment_url": "https://rac.gov.in/",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Bhabha Atomic Research Centre (BARC)": {
        "organisation_name": "Bhabha Atomic Research Centre (BARC)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "barc.gov.in",
        "career_url": "https://www.barc.gov.in/careers/index.html",
        "recruitment_url": "https://recruit.barc.gov.in/",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Bharat Electronics Limited (BEL)": {
        "organisation_name": "Bharat Electronics Limited (BEL)",
        "organisation_type": "psu",
        "government_level": "central",
        "official_domain": "bel-india.in",
        "career_url": "https://bel-india.in/careers/",
        "recruitment_url": "https://bel-india.in/careers/",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Bharat Heavy Electricals Limited (BHEL)": {
        "organisation_name": "Bharat Heavy Electricals Limited (BHEL)",
        "organisation_type": "psu",
        "government_level": "central",
        "official_domain": "bhel.com",
        "career_url": "https://careers.bhel.in/",
        "recruitment_url": "https://careers.bhel.in/",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },

    # ==========================================
    # 5. CSIR LABORATORIES (37 LABORATORIES)
    # ==========================================
    "Council of Scientific & Industrial Research (CSIR)": {
        "organisation_name": "Council of Scientific & Industrial Research (CSIR)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "csir.res.in",
        "career_url": "https://www.csir.res.in/career-opportunities/recruitment",
        "recruitment_url": "https://www.csir.res.in/career-opportunities/recruitment",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "CSIR - National Chemical Laboratory (NCL)": {
        "organisation_name": "CSIR - National Chemical Laboratory (NCL)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "ncl-india.org",
        "career_url": "https://academic.ncl.res.in/career",
        "recruitment_url": "https://academic.ncl.res.in/career",
        "parent_organisation": "Council of Scientific & Industrial Research (CSIR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "CSIR - Central Drug Research Institute (CDRI)": {
        "organisation_name": "CSIR - Central Drug Research Institute (CDRI)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "cdri.res.in",
        "career_url": "https://cdri.res.in/career.php",
        "recruitment_url": "https://cdri.res.in/career.php",
        "parent_organisation": "Council of Scientific & Industrial Research (CSIR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "CSIR - Central Electronics Engineering Research Institute (CEERI)": {
        "organisation_name": "CSIR - Central Electronics Engineering Research Institute (CEERI)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "ceeri.res.in",
        "career_url": "https://www.ceeri.res.in/careers/",
        "recruitment_url": "https://www.ceeri.res.in/careers/",
        "parent_organisation": "Council of Scientific & Industrial Research (CSIR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "CSIR - Centre for Cellular & Molecular Biology (CCMB)": {
        "organisation_name": "CSIR - Centre for Cellular & Molecular Biology (CCMB)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "ccmb.res.in",
        "career_url": "https://www.ccmb.res.in/Careers",
        "recruitment_url": "https://www.ccmb.res.in/Careers",
        "parent_organisation": "Council of Scientific & Industrial Research (CSIR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "CSIR - Institute of Genomics & Integrative Biology (IGIB)": {
        "organisation_name": "CSIR - Institute of Genomics & Integrative Biology (IGIB)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "igib.res.in",
        "career_url": "https://www.igib.res.in/careers",
        "recruitment_url": "https://www.igib.res.in/careers",
        "parent_organisation": "Council of Scientific & Industrial Research (CSIR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "CSIR - Central Food Technological Research Institute (CFTRI)": {
        "organisation_name": "CSIR - Central Food Technological Research Institute (CFTRI)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "cftri.res.in",
        "career_url": "https://cftri.res.in/careers",
        "recruitment_url": "https://cftri.res.in/careers",
        "parent_organisation": "Council of Scientific & Industrial Research (CSIR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "CSIR - National Physical Laboratory (NPL)": {
        "organisation_name": "CSIR - National Physical Laboratory (NPL)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "nplindia.org",
        "career_url": "https://www.nplindia.org/careers",
        "recruitment_url": "https://www.nplindia.org/careers",
        "parent_organisation": "Council of Scientific & Industrial Research (CSIR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },

    # ==========================================
    # 6. ICAR & AGRICULTURAL RESEARCH NETWORK
    # ==========================================
    "Indian Council of Agricultural Research (ICAR)": {
        "organisation_name": "Indian Council of Agricultural Research (ICAR)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "icar.org.in",
        "career_url": "https://icar.org.in/vacancies",
        "recruitment_url": "https://icar.org.in/vacancies",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "ICAR - Indian Agricultural Research Institute (IARI)": {
        "organisation_name": "ICAR - Indian Agricultural Research Institute (IARI)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "iari.res.in",
        "career_url": "https://www.iari.res.in/en/announcement/contractual-jobs.php",
        "recruitment_url": "https://www.iari.res.in/en/announcement/contractual-jobs.php",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "ICAR - Indian Veterinary Research Institute (IVRI)": {
        "organisation_name": "ICAR - Indian Veterinary Research Institute (IVRI)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "ivri.nic.in",
        "career_url": "https://ivri.nic.in/jobs.aspx",
        "recruitment_url": "https://ivri.nic.in/jobs.aspx",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "ICAR - National Dairy Research Institute (NDRI)": {
        "organisation_name": "ICAR - National Dairy Research Institute (NDRI)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "ndri.res.in",
        "career_url": "https://ndri.res.in/jobs/",
        "recruitment_url": "https://ndri.res.in/jobs/",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },

    # ==========================================
    # 7. ICMR & MEDICAL RESEARCH INSTITUTES
    # ==========================================
    "Indian Council of Medical Research (ICMR)": {
        "organisation_name": "Indian Council of Medical Research (ICMR)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "icmr.gov.in",
        "career_url": "https://main.icmr.nic.in/career-opportunity",
        "recruitment_url": "https://main.icmr.nic.in/career-opportunity",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "ICMR - National Institute of Virology (NIV)": {
        "organisation_name": "ICMR - National Institute of Virology (NIV)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "official_domain": "niv.icmr.org.in",
        "career_url": "https://niv.icmr.org.in/career",
        "recruitment_url": "https://niv.icmr.org.in/career",
        "parent_organisation": "Indian Council of Medical Research (ICMR)",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "All India Institute of Medical Sciences New Delhi (AIIMS)": {
        "organisation_name": "All India Institute of Medical Sciences New Delhi (AIIMS)",
        "organisation_type": "hospital",
        "government_level": "central",
        "official_domain": "aiims.edu",
        "career_url": "https://www.aiims.edu/en/notices/recruitment.html",
        "recruitment_url": "https://www.aiims.edu/en/notices/recruitment.html",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },

    # ==========================================
    # 8. PREMIER TECHNICAL INSTITUTES (IITs & NITs)
    # ==========================================
    "Indian Institute of Science (IISc)": {
        "organisation_name": "Indian Institute of Science (IISc)",
        "organisation_type": "university",
        "government_level": "central",
        "official_domain": "iisc.ac.in",
        "career_url": "https://iisc.ac.in/positions-open/",
        "recruitment_url": "https://iisc.ac.in/positions-open/",
        "confidence_category": "INSTITUTIONAL",
        "confidence": 1.0,
    },
    "Indian Institute of Technology Bombay (IIT Bombay)": {
        "organisation_name": "Indian Institute of Technology Bombay (IIT Bombay)",
        "organisation_type": "university",
        "government_level": "central",
        "official_domain": "iitb.ac.in",
        "career_url": "https://www.iitb.ac.in/en/careers/staff-recruitment",
        "recruitment_url": "https://www.iitb.ac.in/en/careers/staff-recruitment",
        "confidence_category": "INSTITUTIONAL",
        "confidence": 1.0,
    },
    "Indian Institute of Technology Delhi (IIT Delhi)": {
        "organisation_name": "Indian Institute of Technology Delhi (IIT Delhi)",
        "organisation_type": "university",
        "government_level": "central",
        "official_domain": "iitd.ac.in",
        "career_url": "https://home.iitd.ac.in/jobs-iitd.php",
        "recruitment_url": "https://home.iitd.ac.in/jobs-iitd.php",
        "confidence_category": "INSTITUTIONAL",
        "confidence": 1.0,
    },
    "Indian Institute of Technology Madras (IIT Madras)": {
        "organisation_name": "Indian Institute of Technology Madras (IIT Madras)",
        "organisation_type": "university",
        "government_level": "central",
        "official_domain": "iitm.ac.in",
        "career_url": "https://www.iitm.ac.in/careers",
        "recruitment_url": "https://www.iitm.ac.in/careers",
        "confidence_category": "INSTITUTIONAL",
        "confidence": 1.0,
    },
    "Indian Institute of Technology Kanpur (IIT Kanpur)": {
        "organisation_name": "Indian Institute of Technology Kanpur (IIT Kanpur)",
        "organisation_type": "university",
        "government_level": "central",
        "official_domain": "iitk.ac.in",
        "career_url": "https://www.iitk.ac.in/doad/staff-recruitment",
        "recruitment_url": "https://www.iitk.ac.in/doad/staff-recruitment",
        "confidence_category": "INSTITUTIONAL",
        "confidence": 1.0,
    },
    "National Institute of Technology Tiruchirappalli (NIT Trichy)": {
        "organisation_name": "National Institute of Technology Tiruchirappalli (NIT Trichy)",
        "organisation_type": "university",
        "government_level": "central",
        "official_domain": "nitt.edu",
        "career_url": "https://www.nitt.edu/home/other/jobs/",
        "recruitment_url": "https://www.nitt.edu/home/other/jobs/",
        "confidence_category": "INSTITUTIONAL",
        "confidence": 1.0,
    },

    # ==========================================
    # 9. STATE PUBLIC SERVICE COMMISSIONS & GOVERNMENTS (SAMPLE OF 28 STATES + 8 UTS)
    # ==========================================
    "Uttar Pradesh — Public Service Commission": {
        "organisation_name": "Uttar Pradesh Public Service Commission (UPPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Uttar Pradesh",
        "official_domain": "uppsc.up.nic.in",
        "career_url": "https://uppsc.up.nic.in/AllNotifications.aspx",
        "recruitment_url": "https://uppsc.up.nic.in/AllNotifications.aspx",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Uttar Pradesh — Subordinate Services Selection Commission": {
        "organisation_name": "Uttar Pradesh Subordinate Services Selection Commission (UPSSSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Uttar Pradesh",
        "official_domain": "upsssc.gov.in",
        "career_url": "https://upsssc.gov.in/Default.aspx",
        "recruitment_url": "https://upsssc.gov.in/Default.aspx",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Maharashtra — Public Service Commission": {
        "organisation_name": "Maharashtra Public Service Commission (MPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Maharashtra",
        "official_domain": "mpsc.gov.in",
        "career_url": "https://mpsc.gov.in/notices",
        "recruitment_url": "https://mpsc.gov.in/notices",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Karnataka — Public Service Commission": {
        "organisation_name": "Karnataka Public Service Commission (KPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Karnataka",
        "official_domain": "kpsc.kar.nic.in",
        "career_url": "https://kpsc.kar.nic.in/notification.html",
        "recruitment_url": "https://kpsc.kar.nic.in/notification.html",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Tamil Nadu — Public Service Commission": {
        "organisation_name": "Tamil Nadu Public Service Commission (TNPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Tamil Nadu",
        "official_domain": "tnpsc.gov.in",
        "career_url": "https://www.tnpsc.gov.in/English/Notification.aspx",
        "recruitment_url": "https://www.tnpsc.gov.in/English/Notification.aspx",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Kerala — Public Service Commission": {
        "organisation_name": "Kerala Public Service Commission (KPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Kerala",
        "official_domain": "keralapsc.gov.in",
        "career_url": "https://www.keralapsc.gov.in/latest-notifications",
        "recruitment_url": "https://www.keralapsc.gov.in/latest-notifications",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Delhi — Subordinate Services Selection Board": {
        "organisation_name": "Delhi Subordinate Services Selection Board (DSSSB)",
        "organisation_type": "statutory_body",
        "government_level": "ut",
        "state": "Delhi",
        "official_domain": "dsssbonline.nic.in",
        "career_url": "https://dsssb.delhi.gov.in/current-vacancies",
        "recruitment_url": "https://dsssb.delhi.gov.in/current-vacancies",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Bihar — Public Service Commission": {
        "organisation_name": "Bihar Public Service Commission (BPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Bihar",
        "official_domain": "bpsc.bih.nic.in",
        "career_url": "https://bpsc.bih.nic.in/",
        "recruitment_url": "https://bpsc.bih.nic.in/",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "West Bengal — Public Service Commission": {
        "organisation_name": "West Bengal Public Service Commission (WBPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "West Bengal",
        "official_domain": "psc.wb.gov.in",
        "career_url": "https://psc.wb.gov.in/notices",
        "recruitment_url": "https://psc.wb.gov.in/notices",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Rajasthan — Public Service Commission": {
        "organisation_name": "Rajasthan Public Service Commission (RPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Rajasthan",
        "official_domain": "rpsc.rajasthan.gov.in",
        "career_url": "https://rpsc.rajasthan.gov.in/news",
        "recruitment_url": "https://rpsc.rajasthan.gov.in/news",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Madhya Pradesh — Public Service Commission": {
        "organisation_name": "Madhya Pradesh Public Service Commission (MPPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Madhya Pradesh",
        "official_domain": "mppsc.mp.gov.in",
        "career_url": "https://mppsc.mp.gov.in/advertisement",
        "recruitment_url": "https://mppsc.mp.gov.in/advertisement",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Gujarat — Public Service Commission": {
        "organisation_name": "Gujarat Public Service Commission (GPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Gujarat",
        "official_domain": "gpsc.gujarat.gov.in",
        "career_url": "https://gpsc.gujarat.gov.in/Advertisements",
        "recruitment_url": "https://gpsc.gujarat.gov.in/Advertisements",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Assam — Public Service Commission": {
        "organisation_name": "Assam Public Service Commission (APSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Assam",
        "official_domain": "apsc.nic.in",
        "career_url": "https://apsc.nic.in/notifications.asp",
        "recruitment_url": "https://apsc.nic.in/notifications.asp",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Telangana — State Public Service Commission": {
        "organisation_name": "Telangana State Public Service Commission (TSPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Telangana",
        "official_domain": "tspsc.gov.in",
        "career_url": "https://tspsc.gov.in/notifications",
        "recruitment_url": "https://tspsc.gov.in/notifications",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Odisha — Public Service Commission": {
        "organisation_name": "Odisha Public Service Commission (OPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Odisha",
        "official_domain": "opsc.gov.in",
        "career_url": "https://www.opsc.gov.in/Public/WhatsNew.aspx",
        "recruitment_url": "https://www.opsc.gov.in/Public/WhatsNew.aspx",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Punjab — Public Service Commission": {
        "organisation_name": "Punjab Public Service Commission (PPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Punjab",
        "official_domain": "ppsc.gov.in",
        "career_url": "https://ppsc.gov.in/advertisement.aspx",
        "recruitment_url": "https://ppsc.gov.in/advertisement.aspx",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Haryana — Public Service Commission": {
        "organisation_name": "Haryana Public Service Commission (HPSC)",
        "organisation_type": "statutory_body",
        "government_level": "state",
        "state": "Haryana",
        "official_domain": "hpsc.gov.in",
        "career_url": "https://hpsc.gov.in/en-us/Advertisements",
        "recruitment_url": "https://hpsc.gov.in/en-us/Advertisements",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },

    # ==========================================
    # 10. PREMIER URBAN LOCAL BODIES & CORPORATIONS
    # ==========================================
    "Brihanmumbai Municipal Corporation (BMC / MCGM)": {
        "organisation_name": "Brihanmumbai Municipal Corporation (BMC / MCGM)",
        "organisation_type": "municipal_body",
        "government_level": "municipal",
        "state": "Maharashtra",
        "city": "Mumbai",
        "official_domain": "mcgm.gov.in",
        "career_url": "https://portal.mcgm.gov.in/irj/portal/anonymous/qlrecruitment",
        "recruitment_url": "https://portal.mcgm.gov.in/irj/portal/anonymous/qlrecruitment",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Bruhat Bengaluru Mahanagara Palike (BBMP)": {
        "organisation_name": "Bruhat Bengaluru Mahanagara Palike (BBMP)",
        "organisation_type": "municipal_body",
        "government_level": "municipal",
        "state": "Karnataka",
        "city": "Bengaluru",
        "official_domain": "bbmp.gov.in",
        "career_url": "https://bbmp.gov.in/recruitment.html",
        "recruitment_url": "https://bbmp.gov.in/recruitment.html",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Greater Hyderabad Municipal Corporation (GHMC)": {
        "organisation_name": "Greater Hyderabad Municipal Corporation (GHMC)",
        "organisation_type": "municipal_body",
        "government_level": "municipal",
        "state": "Telangana",
        "city": "Hyderabad",
        "official_domain": "ghmc.gov.in",
        "career_url": "https://www.ghmc.gov.in/recruitment",
        "recruitment_url": "https://www.ghmc.gov.in/recruitment",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Municipal Corporation of Delhi (MCD)": {
        "organisation_name": "Municipal Corporation of Delhi (MCD)",
        "organisation_type": "municipal_body",
        "government_level": "municipal",
        "state": "Delhi",
        "city": "Delhi",
        "official_domain": "mcdonline.nic.in",
        "career_url": "https://mcdonline.nic.in/recruitment",
        "recruitment_url": "https://mcdonline.nic.in/recruitment",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
    "Pune Municipal Corporation (PMC)": {
        "organisation_name": "Pune Municipal Corporation (PMC)",
        "organisation_type": "municipal_body",
        "government_level": "municipal",
        "state": "Maharashtra",
        "city": "Pune",
        "official_domain": "pmc.gov.in",
        "career_url": "https://pmc.gov.in/en/recruitment",
        "recruitment_url": "https://pmc.gov.in/en/recruitment",
        "confidence_category": "AUTHORITATIVE",
        "confidence": 1.0,
    },
}
