"""
Government Job Source Discovery — Authoritative Municipal & Local Government Directory
Covers major Municipal Corporations, Urban Development Authorities, and Cantonment Boards across India.
"""

from typing import Dict, Any

MUNICIPAL_REGISTRY: Dict[str, Dict[str, Any]] = {
    # =========================================================================
    # MAJOR MUNICIPAL CORPORATIONS
    # =========================================================================
    "Municipal Corporation of Delhi (MCD)": {
        "organisation_name": "Municipal Corporation of Delhi (MCD)",
        "state": "Delhi",
        "official_domain": "mcdonline.nic.in",
        "career_url": "https://mcdonline.nic.in/portal/circulars",
        "recruitment_url": "https://mcdonline.nic.in/portal/circulars",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Brihanmumbai Municipal Corporation (BMC)": {
        "organisation_name": "Brihanmumbai Municipal Corporation (BMC)",
        "state": "Maharashtra",
        "official_domain": "mcgm.gov.in",
        "career_url": "https://portal.mcgm.gov.in/irj/portal/anonymous/hrrecruitment",
        "recruitment_url": "https://portal.mcgm.gov.in/irj/portal/anonymous/hrrecruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Bruhat Bengaluru Mahanagara Palike (BBMP)": {
        "organisation_name": "Bruhat Bengaluru Mahanagara Palike (BBMP)",
        "state": "Karnataka",
        "official_domain": "bbmp.gov.in",
        "career_url": "https://bbmp.gov.in/recruitment.html",
        "recruitment_url": "https://bbmp.gov.in/recruitment.html",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Greater Chennai Corporation (GCC)": {
        "organisation_name": "Greater Chennai Corporation",
        "state": "Tamil Nadu",
        "official_domain": "chennaicorporation.gov.in",
        "career_url": "https://chennaicorporation.gov.in/gcc/recruitment/",
        "recruitment_url": "https://chennaicorporation.gov.in/gcc/recruitment/",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Kolkata Municipal Corporation (KMC)": {
        "organisation_name": "Kolkata Municipal Corporation",
        "state": "West Bengal",
        "official_domain": "kmcgov.in",
        "career_url": "https://www.kmcgov.in/KMCPortal/jsp/Recruitment.jsp",
        "recruitment_url": "https://www.kmcgov.in/KMCPortal/jsp/Recruitment.jsp",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Greater Hyderabad Municipal Corporation (GHMC)": {
        "organisation_name": "Greater Hyderabad Municipal Corporation",
        "state": "Telangana",
        "official_domain": "ghmc.gov.in",
        "career_url": "https://www.ghmc.gov.in/Recruitment",
        "recruitment_url": "https://www.ghmc.gov.in/Recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ahmedabad Municipal Corporation (AMC)": {
        "organisation_name": "Ahmedabad Municipal Corporation",
        "state": "Gujarat",
        "official_domain": "ahmedabadcity.gov.in",
        "career_url": "https://ahmedabadcity.gov.in/portal/jsp/recruitment.jsp",
        "recruitment_url": "https://ahmedabadcity.gov.in/portal/jsp/recruitment.jsp",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Pune Municipal Corporation (PMC)": {
        "organisation_name": "Pune Municipal Corporation",
        "state": "Maharashtra",
        "official_domain": "pmc.gov.in",
        "career_url": "https://pmc.gov.in/en/recruitment",
        "recruitment_url": "https://pmc.gov.in/en/recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Surat Municipal Corporation (SMC)": {
        "organisation_name": "Surat Municipal Corporation",
        "state": "Gujarat",
        "official_domain": "suratmunicipal.gov.in",
        "career_url": "https://www.suratmunicipal.gov.in/Jobs",
        "recruitment_url": "https://www.suratmunicipal.gov.in/Jobs",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Jaipur Municipal Corporation": {
        "organisation_name": "Jaipur Municipal Corporation",
        "state": "Rajasthan",
        "official_domain": "jaipurmc.org",
        "career_url": "http://jaipurmc.org/Recruitment.aspx",
        "recruitment_url": "http://jaipurmc.org/Recruitment.aspx",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Lucknow Municipal Corporation": {
        "organisation_name": "Lucknow Municipal Corporation",
        "state": "Uttar Pradesh",
        "official_domain": "lmc.up.nic.in",
        "career_url": "http://lmc.up.nic.in/recruitment.aspx",
        "recruitment_url": "http://lmc.up.nic.in/recruitment.aspx",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Kanpur Municipal Corporation": {
        "organisation_name": "Kanpur Municipal Corporation",
        "state": "Uttar Pradesh",
        "official_domain": "kmc.up.nic.in",
        "career_url": "http://kmc.up.nic.in/recruitment.aspx",
        "recruitment_url": "http://kmc.up.nic.in/recruitment.aspx",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indore Municipal Corporation": {
        "organisation_name": "Indore Municipal Corporation",
        "state": "Madhya Pradesh",
        "official_domain": "imcindore.mp.gov.in",
        "career_url": "https://imcindore.mp.gov.in/recruitment",
        "recruitment_url": "https://imcindore.mp.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Bhopal Municipal Corporation": {
        "organisation_name": "Bhopal Municipal Corporation",
        "state": "Madhya Pradesh",
        "official_domain": "bhopalcorporation.com",
        "career_url": "https://bhopalcorporation.com/recruitment",
        "recruitment_url": "https://bhopalcorporation.com/recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Nagpur Municipal Corporation": {
        "organisation_name": "Nagpur Municipal Corporation",
        "state": "Maharashtra",
        "official_domain": "nmcnagpur.gov.in",
        "career_url": "https://www.nmcnagpur.gov.in/recruitment",
        "recruitment_url": "https://www.nmcnagpur.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Thane Municipal Corporation": {
        "organisation_name": "Thane Municipal Corporation",
        "state": "Maharashtra",
        "official_domain": "thanecity.gov.in",
        "career_url": "https://thanecity.gov.in/en/recruitment",
        "recruitment_url": "https://thanecity.gov.in/en/recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Pimpri Chinchwad Municipal Corporation (PCMC)": {
        "organisation_name": "Pimpri Chinchwad Municipal Corporation",
        "state": "Maharashtra",
        "official_domain": "pcmcindia.gov.in",
        "career_url": "https://www.pcmcindia.gov.in/recruitment.php",
        "recruitment_url": "https://www.pcmcindia.gov.in/recruitment.php",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Patna Municipal Corporation": {
        "organisation_name": "Patna Municipal Corporation",
        "state": "Bihar",
        "official_domain": "pmc.bihar.gov.in",
        "career_url": "https://pmc.bihar.gov.in/recruitment.aspx",
        "recruitment_url": "https://pmc.bihar.gov.in/recruitment.aspx",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Vadodara Municipal Corporation (VMC)": {
        "organisation_name": "Vadodara Municipal Corporation",
        "state": "Gujarat",
        "official_domain": "vmc.gov.in",
        "career_url": "https://vmc.gov.in/Recruitment.aspx",
        "recruitment_url": "https://vmc.gov.in/Recruitment.aspx",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Greater Visakhapatnam Municipal Corporation (GVMC)": {
        "organisation_name": "Greater Visakhapatnam Municipal Corporation",
        "state": "Andhra Pradesh",
        "official_domain": "gvmc.gov.in",
        "career_url": "https://www.gvmc.gov.in/recruitment",
        "recruitment_url": "https://www.gvmc.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Municipal Corporation Chandigarh": {
        "organisation_name": "Municipal Corporation Chandigarh",
        "state": "Chandigarh",
        "official_domain": "mcchandigarh.gov.in",
        "career_url": "https://mcchandigarh.gov.in/recruitment.php",
        "recruitment_url": "https://mcchandigarh.gov.in/recruitment.php",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Coimbatore City Municipal Corporation": {
        "organisation_name": "Coimbatore City Municipal Corporation",
        "state": "Tamil Nadu",
        "official_domain": "ccmc.gov.in",
        "career_url": "https://www.ccmc.gov.in/recruitment",
        "recruitment_url": "https://www.ccmc.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # URBAN DEVELOPMENT AUTHORITIES
    # =========================================================================
    "Delhi Development Authority (DDA)": {
        "organisation_name": "Delhi Development Authority (DDA)",
        "state": "Delhi",
        "official_domain": "dda.gov.in",
        "career_url": "https://dda.gov.in/jobs",
        "recruitment_url": "https://dda.gov.in/jobs",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Mumbai Metropolitan Region Development Authority (MMRDA)": {
        "organisation_name": "Mumbai Metropolitan Region Development Authority (MMRDA)",
        "state": "Maharashtra",
        "official_domain": "mmrda.maharashtra.gov.in",
        "career_url": "https://mmrda.maharashtra.gov.in/tenders-recruitments",
        "recruitment_url": "https://mmrda.maharashtra.gov.in/tenders-recruitments",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Bangalore Development Authority (BDA)": {
        "organisation_name": "Bangalore Development Authority (BDA)",
        "state": "Karnataka",
        "official_domain": "bdabangalore.org",
        "career_url": "https://bdabangalore.org/recruitment.html",
        "recruitment_url": "https://bdabangalore.org/recruitment.html",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "New Okhla Industrial Development Authority (NOIDA)": {
        "organisation_name": "New Okhla Industrial Development Authority (NOIDA)",
        "state": "Uttar Pradesh",
        "official_domain": "noidaauthorityonline.in",
        "career_url": "https://noidaauthorityonline.in/recruitment.html",
        "recruitment_url": "https://noidaauthorityonline.in/recruitment.html",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Greater Noida Industrial Development Authority (GNIDA)": {
        "organisation_name": "Greater Noida Industrial Development Authority (GNIDA)",
        "state": "Uttar Pradesh",
        "official_domain": "greaternoidaauthority.in",
        "career_url": "https://www.greaternoidaauthority.in/recruitment",
        "recruitment_url": "https://www.greaternoidaauthority.in/recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Hyderabad Metropolitan Development Authority (HMDA)": {
        "organisation_name": "Hyderabad Metropolitan Development Authority (HMDA)",
        "state": "Telangana",
        "official_domain": "hmda.gov.in",
        "career_url": "https://www.hmda.gov.in/notifications",
        "recruitment_url": "https://www.hmda.gov.in/notifications",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Chennai Metropolitan Development Authority (CMDA)": {
        "organisation_name": "Chennai Metropolitan Development Authority (CMDA)",
        "state": "Tamil Nadu",
        "official_domain": "cmdachennai.gov.in",
        "career_url": "http://www.cmdachennai.gov.in/recruitment.html",
        "recruitment_url": "http://www.cmdachennai.gov.in/recruitment.html",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Gurugram Metropolitan Development Authority (GMDA)": {
        "organisation_name": "Gurugram Metropolitan Development Authority (GMDA)",
        "state": "Haryana",
        "official_domain": "gmda.gov.in",
        "career_url": "https://gmda.gov.in/recruitment",
        "recruitment_url": "https://gmda.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Kolkata Metropolitan Development Authority (KMDA)": {
        "organisation_name": "Kolkata Metropolitan Development Authority (KMDA)",
        "state": "West Bengal",
        "official_domain": "kmda.wb.gov.in",
        "career_url": "https://kmda.wb.gov.in/notices/recruitment",
        "recruitment_url": "https://kmda.wb.gov.in/notices/recruitment",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # CANTONMENT BOARDS
    # =========================================================================
    "Pune Cantonment Board": {
        "organisation_name": "Pune Cantonment Board",
        "state": "Maharashtra",
        "official_domain": "pune.cantt.gov.in",
        "career_url": "https://pune.cantt.gov.in/recruitment/",
        "recruitment_url": "https://pune.cantt.gov.in/recruitment/",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Delhi Cantonment Board": {
        "organisation_name": "Delhi Cantonment Board",
        "state": "Delhi",
        "official_domain": "delhi.cantt.gov.in",
        "career_url": "https://delhi.cantt.gov.in/recruitment/",
        "recruitment_url": "https://delhi.cantt.gov.in/recruitment/",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Agra Cantonment Board": {
        "organisation_name": "Agra Cantonment Board",
        "state": "Uttar Pradesh",
        "official_domain": "agra.cantt.gov.in",
        "career_url": "https://agra.cantt.gov.in/recruitment/",
        "recruitment_url": "https://agra.cantt.gov.in/recruitment/",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Lucknow Cantonment Board": {
        "organisation_name": "Lucknow Cantonment Board",
        "state": "Uttar Pradesh",
        "official_domain": "lucknow.cantt.gov.in",
        "career_url": "https://lucknow.cantt.gov.in/recruitment/",
        "recruitment_url": "https://lucknow.cantt.gov.in/recruitment/",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Secunderabad Cantonment Board": {
        "organisation_name": "Secunderabad Cantonment Board",
        "state": "Telangana",
        "official_domain": "secunderabad.cantt.gov.in",
        "career_url": "https://secunderabad.cantt.gov.in/recruitment/",
        "recruitment_url": "https://secunderabad.cantt.gov.in/recruitment/",
        "source_type": "portal",
        "government_level": "municipal",
        "confidence_category": "AUTHORITATIVE",
    },
    "Directorate General Defence Estates (DGDE / Cantt Boards)": {
        "organisation_name": "Directorate General Defence Estates (DGDE)",
        "state": "Delhi",
        "official_domain": "dgde.gov.in",
        "career_url": "https://www.dgde.gov.in/recruitment",
        "recruitment_url": "https://www.dgde.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
}
