"""
Government Job Source Discovery — Authoritative Central Ministries, PSUs & Financial Institutions Directory
Covers:
- Unresolved Central Ministries & Apex Departments (MoEFCC, Railways, Power, etc.)
- Maharatna, Navratna, & Miniratna CPSEs
- Metro Rail Corporations
- Public Sector Banks & Regulators
- Key Digital Government Missions (GSTN, MyGov, I4C, NKN, Bhashini)
"""

from typing import Dict, Any

PSU_AND_CENTRAL_REGISTRY: Dict[str, Dict[str, Any]] = {
    # =========================================================================
    # CENTRAL MINISTRIES & APEX DEPARTMENTS
    # =========================================================================
    "Ministry of Environment, Forest & Climate Change": {
        "organisation_name": "Ministry of Environment, Forest & Climate Change",
        "state": "Delhi",
        "official_domain": "moef.gov.in",
        "career_url": "https://moef.gov.in/en/recruitment-rules/",
        "recruitment_url": "https://moef.gov.in/en/recruitment-rules/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Railways": {
        "organisation_name": "Ministry of Railways",
        "state": "Delhi",
        "official_domain": "indianrailways.gov.in",
        "career_url": "https://indianrailways.gov.in/railwayboard/view_section.jsp?lang=0&id=0,1,304,366",
        "recruitment_url": "https://indianrailways.gov.in/railwayboard/view_section.jsp?lang=0&id=0,1,304,366",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Railway Recruitment Cells (RRC)": {
        "organisation_name": "Railway Recruitment Control Board / RRC",
        "parent_organisation": "Ministry of Railways",
        "state": "Delhi",
        "official_domain": "rrcb.gov.in",
        "career_url": "https://www.rrcb.gov.in/",
        "recruitment_url": "https://www.rrcb.gov.in/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Communications": {
        "organisation_name": "Ministry of Communications",
        "state": "Delhi",
        "official_domain": "dot.gov.in",
        "career_url": "https://dot.gov.in/vacancies",
        "recruitment_url": "https://dot.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Power": {
        "organisation_name": "Ministry of Power",
        "state": "Delhi",
        "official_domain": "powermin.gov.in",
        "career_url": "https://powermin.gov.in/en/content/vacancies",
        "recruitment_url": "https://powermin.gov.in/en/content/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Department of Higher Education": {
        "organisation_name": "Department of Higher Education",
        "parent_organisation": "Ministry of Education",
        "state": "Delhi",
        "official_domain": "education.gov.in",
        "career_url": "https://www.education.gov.in/advertisements",
        "recruitment_url": "https://www.education.gov.in/advertisements",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Department of School Education & Literacy": {
        "organisation_name": "Department of School Education & Literacy",
        "parent_organisation": "Ministry of Education",
        "state": "Delhi",
        "official_domain": "dsel.education.gov.in",
        "career_url": "https://dsel.education.gov.in/vacancies",
        "recruitment_url": "https://dsel.education.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Textiles": {
        "organisation_name": "Ministry of Textiles",
        "state": "Delhi",
        "official_domain": "texmin.nic.in",
        "career_url": "http://texmin.nic.in/vacancies",
        "recruitment_url": "http://texmin.nic.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Commerce & Industry": {
        "organisation_name": "Ministry of Commerce & Industry",
        "state": "Delhi",
        "official_domain": "commerce.gov.in",
        "career_url": "https://commerce.gov.in/vacancies/",
        "recruitment_url": "https://commerce.gov.in/vacancies/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Department for Promotion of Industry and Internal Trade (DPIIT)": {
        "organisation_name": "Department for Promotion of Industry and Internal Trade (DPIIT)",
        "parent_organisation": "Ministry of Commerce & Industry",
        "state": "Delhi",
        "official_domain": "dpiit.gov.in",
        "career_url": "https://dpiit.gov.in/vacancies",
        "recruitment_url": "https://dpiit.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Jal Shakti": {
        "organisation_name": "Ministry of Jal Shakti",
        "state": "Delhi",
        "official_domain": "jalshakti-dowr.gov.in",
        "career_url": "https://jalshakti-dowr.gov.in/vacancies/",
        "recruitment_url": "https://jalshakti-dowr.gov.in/vacancies/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Chemicals & Fertilizers": {
        "organisation_name": "Ministry of Chemicals & Fertilizers",
        "state": "Delhi",
        "official_domain": "chemicals.gov.in",
        "career_url": "https://chemicals.gov.in/vacancies",
        "recruitment_url": "https://chemicals.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Defence": {
        "organisation_name": "Ministry of Defence",
        "state": "Delhi",
        "official_domain": "mod.gov.in",
        "career_url": "https://www.mod.gov.in/dod/vacancies",
        "recruitment_url": "https://www.mod.gov.in/dod/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Department of Economic Affairs": {
        "organisation_name": "Department of Economic Affairs",
        "parent_organisation": "Ministry of Finance",
        "state": "Delhi",
        "official_domain": "dea.gov.in",
        "career_url": "https://dea.gov.in/vacancies",
        "recruitment_url": "https://dea.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Department of Expenditure": {
        "organisation_name": "Department of Expenditure",
        "parent_organisation": "Ministry of Finance",
        "state": "Delhi",
        "official_domain": "doe.gov.in",
        "career_url": "https://doe.gov.in/vacancies",
        "recruitment_url": "https://doe.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Science & Technology": {
        "organisation_name": "Ministry of Science & Technology (DST)",
        "state": "Delhi",
        "official_domain": "dst.gov.in",
        "career_url": "https://dst.gov.in/recruitment",
        "recruitment_url": "https://dst.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Directorate General of Employment": {
        "organisation_name": "Directorate General of Employment (DGE)",
        "parent_organisation": "Ministry of Labour and Employment",
        "state": "Delhi",
        "official_domain": "dge.gov.in",
        "career_url": "https://dge.gov.in/dge/recruitment",
        "recruitment_url": "https://dge.gov.in/dge/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Tourism": {
        "organisation_name": "Ministry of Tourism",
        "state": "Delhi",
        "official_domain": "tourism.gov.in",
        "career_url": "https://tourism.gov.in/recruitment-and-vacancies",
        "recruitment_url": "https://tourism.gov.in/recruitment-and-vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Rural Development": {
        "organisation_name": "Ministry of Rural Development",
        "state": "Delhi",
        "official_domain": "rural.nic.in",
        "career_url": "https://rural.nic.in/en/documents/vacancies",
        "recruitment_url": "https://rural.nic.in/en/documents/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Law & Justice": {
        "organisation_name": "Ministry of Law & Justice",
        "state": "Delhi",
        "official_domain": "lawmin.gov.in",
        "career_url": "https://lawmin.gov.in/vacancies",
        "recruitment_url": "https://lawmin.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Youth Affairs & Sports": {
        "organisation_name": "Ministry of Youth Affairs & Sports",
        "state": "Delhi",
        "official_domain": "yas.nic.in",
        "career_url": "https://yas.nic.in/vacancies",
        "recruitment_url": "https://yas.nic.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Ministry of Statistics & Programme Implementation": {
        "organisation_name": "Ministry of Statistics & Programme Implementation (MoSPI)",
        "state": "Delhi",
        "official_domain": "mospi.gov.in",
        "career_url": "https://www.mospi.gov.in/vacancies",
        "recruitment_url": "https://www.mospi.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # DIGITAL INDIA & CYBERSECURITY MISSIONS
    # =========================================================================
    "Digital India": {
        "organisation_name": "Digital India Corporation (DIC)",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "state": "Delhi",
        "official_domain": "digitalindia.gov.in",
        "career_url": "https://www.digitalindia.gov.in/careers",
        "recruitment_url": "https://www.digitalindia.gov.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "MyGov": {
        "organisation_name": "MyGov India",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "state": "Delhi",
        "official_domain": "mygov.in",
        "career_url": "https://www.mygov.in/work-at-mygov/",
        "recruitment_url": "https://www.mygov.in/work-at-mygov/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Goods and Services Tax Network (GSTN)": {
        "organisation_name": "Goods and Services Tax Network (GSTN)",
        "state": "Delhi",
        "official_domain": "gstn.org.in",
        "career_url": "https://www.gstn.org.in/careers",
        "recruitment_url": "https://www.gstn.org.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "GOVERNMENT_AFFILIATED",
    },
    "National Knowledge Network (NKN)": {
        "organisation_name": "National Knowledge Network (NKN)",
        "parent_organisation": "National Informatics Centre (NIC)",
        "state": "Delhi",
        "official_domain": "nkn.gov.in",
        "career_url": "https://nkn.gov.in/",
        "recruitment_url": "https://nkn.gov.in/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Digital India Bhashini": {
        "organisation_name": "Digital India Bhashini Division (Bhashini)",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "state": "Delhi",
        "official_domain": "bhashini.gov.in",
        "career_url": "https://bhashini.gov.in/career",
        "recruitment_url": "https://bhashini.gov.in/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Cyber Crime Coordination Centre (I4C)": {
        "organisation_name": "Indian Cyber Crime Coordination Centre (I4C)",
        "parent_organisation": "Ministry of Home Affairs",
        "state": "Delhi",
        "official_domain": "i4c.mha.gov.in",
        "career_url": "https://cybercrime.gov.in/",
        "recruitment_url": "https://cybercrime.gov.in/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Cyber Coordination Centre": {
        "organisation_name": "National Cyber Coordination Centre (NCCC)",
        "parent_organisation": "Ministry of Electronics & Information Technology (MeitY)",
        "state": "Delhi",
        "official_domain": "cert-in.org.in",
        "career_url": "https://www.cert-in.org.in/careers.jsp",
        "recruitment_url": "https://www.cert-in.org.in/careers.jsp",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # METRO RAIL CORPORATIONS
    # =========================================================================
    "Delhi Metro Rail Corporation (DMRC)": {
        "organisation_name": "Delhi Metro Rail Corporation (DMRC)",
        "state": "Delhi",
        "official_domain": "delhimetrorail.com",
        "career_url": "https://www.delhimetrorail.com/career",
        "recruitment_url": "https://www.delhimetrorail.com/career",
        "source_type": "portal",
        "government_level": "state",
        "confidence_category": "AUTHORITATIVE",
    },
    "Gujarat Metro Rail Corporation": {
        "organisation_name": "Gujarat Metro Rail Corporation (GMRC)",
        "state": "Gujarat",
        "official_domain": "gujaratmetrorail.com",
        "career_url": "https://www.gujaratmetrorail.com/careers/",
        "recruitment_url": "https://www.gujaratmetrorail.com/careers/",
        "source_type": "portal",
        "government_level": "state",
        "confidence_category": "AUTHORITATIVE",
    },
    "Maharashtra Metro Rail Corporation": {
        "organisation_name": "Maharashtra Metro Rail Corporation (Maha Metro)",
        "state": "Maharashtra",
        "official_domain": "mahametro.org",
        "career_url": "https://www.mahametro.org/career.aspx",
        "recruitment_url": "https://www.mahametro.org/career.aspx",
        "source_type": "portal",
        "government_level": "state",
        "confidence_category": "AUTHORITATIVE",
    },
    "Madhya Pradesh Metro Rail Corporation": {
        "organisation_name": "Madhya Pradesh Metro Rail Corporation (MPMRCL)",
        "state": "Madhya Pradesh",
        "official_domain": "mpmetrorail.com",
        "career_url": "https://mpmetrorail.com/recruitment.aspx",
        "recruitment_url": "https://mpmetrorail.com/recruitment.aspx",
        "source_type": "portal",
        "government_level": "state",
        "confidence_category": "AUTHORITATIVE",
    },
    "Bangalore Metro Rail Corporation (BMRCL)": {
        "organisation_name": "Bangalore Metro Rail Corporation (BMRCL)",
        "state": "Karnataka",
        "official_domain": "bmrc.co.in",
        "career_url": "https://english.bmrc.co.in/Career",
        "recruitment_url": "https://english.bmrc.co.in/Career",
        "source_type": "portal",
        "government_level": "state",
        "confidence_category": "AUTHORITATIVE",
    },
    "Chennai Metro Rail Limited (CMRL)": {
        "organisation_name": "Chennai Metro Rail Limited (CMRL)",
        "state": "Tamil Nadu",
        "official_domain": "chennaimetrorail.org",
        "career_url": "https://chennaimetrorail.org/careers/",
        "recruitment_url": "https://chennaimetrorail.org/careers/",
        "source_type": "portal",
        "government_level": "state",
        "confidence_category": "AUTHORITATIVE",
    },
    "Uttar Pradesh Metro Rail Corporation (UPMRC)": {
        "organisation_name": "Uttar Pradesh Metro Rail Corporation (UPMRC)",
        "state": "Uttar Pradesh",
        "official_domain": "lmrcl.com",
        "career_url": "https://www.lmrcl.com/recruitment",
        "recruitment_url": "https://www.lmrcl.com/recruitment",
        "source_type": "portal",
        "government_level": "state",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # MAJOR CPSEs & PSUs
    # =========================================================================
    "NTPC Limited": {
        "organisation_name": "NTPC Limited",
        "state": "Delhi",
        "official_domain": "ntpc.co.in",
        "career_url": "https://www.ntpc.co.in/en/careers",
        "recruitment_url": "https://www.ntpc.co.in/en/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Bharat Heavy Electricals Limited (BHEL)": {
        "organisation_name": "Bharat Heavy Electricals Limited (BHEL)",
        "state": "Delhi",
        "official_domain": "bhel.com",
        "career_url": "https://careers.bhel.in/",
        "recruitment_url": "https://careers.bhel.in/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Oil and Natural Gas Corporation (ONGC)": {
        "organisation_name": "Oil and Natural Gas Corporation (ONGC)",
        "state": "Delhi",
        "official_domain": "ongcindia.com",
        "career_url": "https://ongcindia.com/web/eng/career",
        "recruitment_url": "https://ongcindia.com/web/eng/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Oil Corporation Limited (IOCL)": {
        "organisation_name": "Indian Oil Corporation Limited (IOCL)",
        "state": "Delhi",
        "official_domain": "iocl.com",
        "career_url": "https://iocl.com/latest-job-opening",
        "recruitment_url": "https://iocl.com/latest-job-opening",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Power Grid Corporation of India (POWERGRID)": {
        "organisation_name": "Power Grid Corporation of India",
        "state": "Haryana",
        "official_domain": "powergrid.in",
        "career_url": "https://www.powergrid.in/job-opportunities",
        "recruitment_url": "https://www.powergrid.in/job-opportunities",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Coal India Limited (CIL)": {
        "organisation_name": "Coal India Limited (CIL)",
        "state": "West Bengal",
        "official_domain": "coalindia.in",
        "career_url": "https://www.coalindia.in/career-cil/",
        "recruitment_url": "https://www.coalindia.in/career-cil/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Steel Authority of India Limited (SAIL)": {
        "organisation_name": "Steel Authority of India Limited (SAIL)",
        "state": "Delhi",
        "official_domain": "sail.co.in",
        "career_url": "https://www.sail.co.in/en/careers",
        "recruitment_url": "https://www.sail.co.in/en/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "GAIL (India) Limited": {
        "organisation_name": "GAIL (India) Limited",
        "state": "Delhi",
        "official_domain": "gailonline.com",
        "career_url": "https://gailonline.com/CRApplyingGail.html",
        "recruitment_url": "https://gailonline.com/CRApplyingGail.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Oil India Limited": {
        "organisation_name": "Oil India Limited",
        "state": "Assam",
        "official_domain": "oil-india.com",
        "career_url": "https://www.oil-india.com/current-openings",
        "recruitment_url": "https://www.oil-india.com/current-openings",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Hindustan Aeronautics Limited (HAL)": {
        "organisation_name": "Hindustan Aeronautics Limited (HAL)",
        "state": "Karnataka",
        "official_domain": "hal-india.co.in",
        "career_url": "https://hal-india.co.in/Career/M__64",
        "recruitment_url": "https://hal-india.co.in/Career/M__64",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Bharat Electronics Limited (BEL)": {
        "organisation_name": "Bharat Electronics Limited (BEL)",
        "state": "Karnataka",
        "official_domain": "bel-india.in",
        "career_url": "https://bel-india.in/careers/",
        "recruitment_url": "https://bel-india.in/careers/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Highways Authority of India (NHAI)": {
        "organisation_name": "National Highways Authority of India (NHAI)",
        "state": "Delhi",
        "official_domain": "nhai.gov.in",
        "career_url": "https://nhai.gov.in/vacancies",
        "recruitment_url": "https://nhai.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "RailTel Corporation of India": {
        "organisation_name": "RailTel Corporation of India",
        "state": "Haryana",
        "official_domain": "railtelindia.com",
        "career_url": "https://www.railtelindia.com/careers.html",
        "recruitment_url": "https://www.railtelindia.com/careers.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Railway Catering and Tourism Corporation (IRCTC)": {
        "organisation_name": "Indian Railway Catering and Tourism Corporation (IRCTC)",
        "state": "Delhi",
        "official_domain": "irctc.co.in",
        "career_url": "https://www.irctc.co.in/eticketing/careers.html",
        "recruitment_url": "https://www.irctc.co.in/eticketing/careers.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "RITES Limited": {
        "organisation_name": "RITES Limited",
        "state": "Haryana",
        "official_domain": "rites.com",
        "career_url": "https://www.rites.com/career",
        "recruitment_url": "https://www.rites.com/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "IRCON International Limited": {
        "organisation_name": "IRCON International Limited",
        "state": "Delhi",
        "official_domain": "ircon.org",
        "career_url": "https://www.ircon.org/index.php?option=com_content&view=article&id=46&Itemid=154&lang=en",
        "recruitment_url": "https://www.ircon.org/index.php?option=com_content&view=article&id=46&Itemid=154&lang=en",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Solar Energy Corporation of India (SECI)": {
        "organisation_name": "Solar Energy Corporation of India (SECI)",
        "state": "Delhi",
        "official_domain": "seci.co.in",
        "career_url": "https://www.seci.co.in/careers",
        "recruitment_url": "https://www.seci.co.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Renewable Energy Development Agency (IREDA)": {
        "organisation_name": "Indian Renewable Energy Development Agency (IREDA)",
        "state": "Delhi",
        "official_domain": "ireda.in",
        "career_url": "https://www.ireda.in/careers",
        "recruitment_url": "https://www.ireda.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # PUBLIC SECTOR BANKS
    # =========================================================================
    "Punjab National Bank": {
        "organisation_name": "Punjab National Bank",
        "state": "Delhi",
        "official_domain": "pnbindia.in",
        "career_url": "https://www.pnbindia.in/recruitments.aspx",
        "recruitment_url": "https://www.pnbindia.in/recruitments.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "State Bank of India": {
        "organisation_name": "State Bank of India",
        "state": "Maharashtra",
        "official_domain": "sbi.co.in",
        "career_url": "https://sbi.co.in/web/careers",
        "recruitment_url": "https://sbi.co.in/web/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Bank of Baroda": {
        "organisation_name": "Bank of Baroda",
        "state": "Gujarat",
        "official_domain": "bankofbaroda.in",
        "career_url": "https://www.bankofbaroda.in/career-detail",
        "recruitment_url": "https://www.bankofbaroda.in/career-detail",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Canara Bank": {
        "organisation_name": "Canara Bank",
        "state": "Karnataka",
        "official_domain": "canarabank.com",
        "career_url": "https://canarabank.com/pages/recruitment",
        "recruitment_url": "https://canarabank.com/pages/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Union Bank of India": {
        "organisation_name": "Union Bank of India",
        "state": "Maharashtra",
        "official_domain": "unionbankofindia.co.in",
        "career_url": "https://www.unionbankofindia.co.in/english/recruitment.aspx",
        "recruitment_url": "https://www.unionbankofindia.co.in/english/recruitment.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Bank": {
        "organisation_name": "Indian Bank",
        "state": "Tamil Nadu",
        "official_domain": "indianbank.in",
        "career_url": "https://www.indianbank.in/career/",
        "recruitment_url": "https://www.indianbank.in/career/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    # =========================================================================
    # APEX REGULATORS, COMMISSIONS & STATUTORY AUTHORITIES
    # =========================================================================
    "Reserve Bank of India (RBI)": {
        "organisation_name": "Reserve Bank of India (RBI)",
        "state": "Maharashtra",
        "official_domain": "rbi.org.in",
        "career_url": "https://opportunities.rbi.org.in/scripts/vacancies.aspx",
        "recruitment_url": "https://opportunities.rbi.org.in/scripts/vacancies.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Securities and Exchange Board of India (SEBI)": {
        "organisation_name": "Securities and Exchange Board of India (SEBI)",
        "state": "Maharashtra",
        "official_domain": "sebi.gov.in",
        "career_url": "https://www.sebi.gov.in/department/human-resources-department-37/careers.html",
        "recruitment_url": "https://www.sebi.gov.in/department/human-resources-department-37/careers.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Pension Fund Regulatory and Development Authority (PFRDA)": {
        "organisation_name": "Pension Fund Regulatory and Development Authority (PFRDA)",
        "state": "Delhi",
        "official_domain": "pfrda.org.in",
        "career_url": "https://www.pfrda.org.in/index1.cshtml?lsid=16",
        "recruitment_url": "https://www.pfrda.org.in/index1.cshtml?lsid=16",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Telecom Regulatory Authority of India (TRAI)": {
        "organisation_name": "Telecom Regulatory Authority of India (TRAI)",
        "state": "Delhi",
        "official_domain": "trai.gov.in",
        "career_url": "https://trai.gov.in/vacancies-notifications",
        "recruitment_url": "https://trai.gov.in/vacancies-notifications",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Competition Commission of India (CCI)": {
        "organisation_name": "Competition Commission of India (CCI)",
        "state": "Delhi",
        "official_domain": "cci.gov.in",
        "career_url": "https://www.cci.gov.in/careers",
        "recruitment_url": "https://www.cci.gov.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Green Tribunal (NGT)": {
        "organisation_name": "National Green Tribunal (NGT)",
        "state": "Delhi",
        "official_domain": "greentribunal.gov.in",
        "career_url": "https://greentribunal.gov.in/recruitment",
        "recruitment_url": "https://greentribunal.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Central Information Commission (CIC)": {
        "organisation_name": "Central Information Commission (CIC)",
        "state": "Delhi",
        "official_domain": "cic.gov.in",
        "career_url": "https://cic.gov.in/vacancies",
        "recruitment_url": "https://cic.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Central Vigilance Commission (CVC)": {
        "organisation_name": "Central Vigilance Commission (CVC)",
        "state": "Delhi",
        "official_domain": "cvc.gov.in",
        "career_url": "https://cvc.gov.in/vacancies",
        "recruitment_url": "https://cvc.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Central Water Commission (CWC)": {
        "organisation_name": "Central Water Commission (CWC)",
        "state": "Delhi",
        "official_domain": "cwc.gov.in",
        "career_url": "https://cwc.gov.in/recruitment",
        "recruitment_url": "https://cwc.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Staff Selection Commission (SSC)": {
        "organisation_name": "Staff Selection Commission (SSC)",
        "state": "Delhi",
        "official_domain": "ssc.gov.in",
        "career_url": "https://ssc.gov.in/notices",
        "recruitment_url": "https://ssc.gov.in/notices",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Union Public Service Commission (UPSC)": {
        "organisation_name": "Union Public Service Commission (UPSC)",
        "state": "Delhi",
        "official_domain": "upsc.gov.in",
        "career_url": "https://upsc.gov.in/recruitment",
        "recruitment_url": "https://upsc.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Testing Agency (NTA)": {
        "organisation_name": "National Testing Agency (NTA)",
        "state": "Delhi",
        "official_domain": "nta.ac.in",
        "career_url": "https://nta.ac.in/Notice",
        "recruitment_url": "https://nta.ac.in/Notice",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "University Grants Commission (UGC)": {
        "organisation_name": "University Grants Commission (UGC)",
        "state": "Delhi",
        "official_domain": "ugc.ac.in",
        "career_url": "https://www.ugc.ac.in/ugc_jobs.aspx",
        "recruitment_url": "https://www.ugc.ac.in/ugc_jobs.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Commission for Women (NCW)": {
        "organisation_name": "National Commission for Women (NCW)",
        "state": "Delhi",
        "official_domain": "ncw.nic.in",
        "career_url": "http://ncw.nic.in/notice/vacancies",
        "recruitment_url": "http://ncw.nic.in/notice/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Commission for Scheduled Castes": {
        "organisation_name": "National Commission for Scheduled Castes",
        "state": "Delhi",
        "official_domain": "ncsc.nic.in",
        "career_url": "https://ncsc.nic.in/vacancies",
        "recruitment_url": "https://ncsc.nic.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Land Ports Authority of India (LPAI)": {
        "organisation_name": "Land Ports Authority of India (LPAI)",
        "state": "Delhi",
        "official_domain": "lpai.gov.in",
        "career_url": "https://lpai.gov.in/vacancies",
        "recruitment_url": "https://lpai.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Industrial Corridor Development Corporation (NICDC)": {
        "organisation_name": "National Industrial Corridor Development Corporation (NICDC)",
        "state": "Delhi",
        "official_domain": "nicdc.in",
        "career_url": "https://nicdc.in/careers",
        "recruitment_url": "https://nicdc.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    # =========================================================================
    # FINANCIAL INSTITUTIONS & CPSEs
    # =========================================================================
    "Life Insurance Corporation of India (LIC)": {
        "organisation_name": "Life Insurance Corporation of India",
        "state": "Maharashtra",
        "official_domain": "licindia.in",
        "career_url": "https://licindia.in/Bottom-Links/careers",
        "recruitment_url": "https://licindia.in/Bottom-Links/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Power Finance Corporation (PFC)": {
        "organisation_name": "Power Finance Corporation Limited (PFC)",
        "state": "Delhi",
        "official_domain": "pfcindia.com",
        "career_url": "https://pfcindia.com/Career",
        "recruitment_url": "https://pfcindia.com/Career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "REC Limited": {
        "organisation_name": "REC Limited",
        "state": "Delhi",
        "official_domain": "recindia.nic.in",
        "career_url": "https://recindia.nic.in/careers",
        "recruitment_url": "https://recindia.nic.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Small Industries Development Bank of India (SIDBI)": {
        "organisation_name": "Small Industries Development Bank of India (SIDBI)",
        "state": "Uttar Pradesh",
        "official_domain": "sidbi.in",
        "career_url": "https://www.sidbi.in/en/careers",
        "recruitment_url": "https://www.sidbi.in/en/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Bank for Agriculture and Rural Development (NABARD)": {
        "organisation_name": "National Bank for Agriculture and Rural Development (NABARD)",
        "state": "Maharashtra",
        "official_domain": "nabard.org",
        "career_url": "https://www.nabard.org/careers-notices.aspx",
        "recruitment_url": "https://www.nabard.org/careers-notices.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Export-Import Bank of India (EXIM Bank)": {
        "organisation_name": "Export-Import Bank of India (EXIM Bank)",
        "state": "Maharashtra",
        "official_domain": "eximbankindia.in",
        "career_url": "https://www.eximbankindia.in/careers",
        "recruitment_url": "https://www.eximbankindia.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Food Corporation of India (FCI)": {
        "organisation_name": "Food Corporation of India (FCI)",
        "state": "Delhi",
        "official_domain": "fci.gov.in",
        "career_url": "https://fci.gov.in/current-recruitment.php",
        "recruitment_url": "https://fci.gov.in/current-recruitment.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Highways Authority of India (NHAI)": {
        "organisation_name": "National Highways Authority of India (NHAI)",
        "state": "Delhi",
        "official_domain": "nhai.gov.in",
        "career_url": "https://nhai.gov.in/#/vacancies",
        "recruitment_url": "https://nhai.gov.in/#/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Solar Energy Corporation of India (SECI)": {
        "organisation_name": "Solar Energy Corporation of India (SECI)",
        "state": "Delhi",
        "official_domain": "seci.co.in",
        "career_url": "https://www.seci.co.in/careers",
        "recruitment_url": "https://www.seci.co.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Eastern Coalfields Limited": {
        "organisation_name": "Eastern Coalfields Limited",
        "state": "West Bengal",
        "official_domain": "easterncoal.nic.in",
        "career_url": "http://www.easterncoal.nic.in/recruitment.html",
        "recruitment_url": "http://www.easterncoal.nic.in/recruitment.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Skill Development Corporation": {
        "organisation_name": "National Skill Development Corporation (NSDC)",
        "state": "Delhi",
        "official_domain": "nsdcindia.org",
        "career_url": "https://nsdcindia.org/careers",
        "recruitment_url": "https://nsdcindia.org/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "MyGov": {
        "organisation_name": "MyGov",
        "state": "Delhi",
        "official_domain": "mygov.in",
        "career_url": "https://www.mygov.in/work-at-mygov/",
        "recruitment_url": "https://www.mygov.in/work-at-mygov/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National API Exchange (NAPIX)": {
        "organisation_name": "National API Exchange (NAPIX / API Setu)",
        "state": "Delhi",
        "official_domain": "apisetu.gov.in",
        "career_url": "https://apisetu.gov.in",
        "recruitment_url": "https://apisetu.gov.in",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
}
