"""
Government Job Source Discovery — Authoritative Research & Higher Education Directory
Covers:
- All 37 CSIR National Laboratories
- All 27 ICMR National Institutes
- Major ICAR National Research Institutes
- All 23 Indian Institutes of Technology (IITs)
- All 31 National Institutes of Technology (NITs)
- All 25 Indian Institutes of Information Technology (IIITs)
- AIIMS Institutes (All India Institute of Medical Sciences)
- Central Universities
- Autonomous S&T Research Institutes (DST, DBT, DAE, MoES, DOS)
"""

from typing import Dict, Any

RESEARCH_REGISTRY: Dict[str, Dict[str, Any]] = {
    # =========================================================================
    # CSIR NATIONAL LABORATORIES (All 37 Labs)
    # =========================================================================
    "CSIR - National Chemical Laboratory (CSIR-NCL)": {
        "organisation_name": "CSIR - National Chemical Laboratory (CSIR-NCL)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Maharashtra",
        "official_domain": "ncl-india.org",
        "career_url": "https://www.ncl-india.org/files/Career/CurrentOpportunities.aspx",
        "recruitment_url": "https://www.ncl-india.org/files/Career/CurrentOpportunities.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - National Physical Laboratory (CSIR-NPL)": {
        "organisation_name": "CSIR - National Physical Laboratory (CSIR-NPL)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Delhi",
        "official_domain": "nplindia.org",
        "career_url": "https://www.nplindia.org/index.php/careers/",
        "recruitment_url": "https://www.nplindia.org/index.php/careers/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Drug Research Institute (CSIR-CDRI)": {
        "organisation_name": "CSIR - Central Drug Research Institute (CSIR-CDRI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Uttar Pradesh",
        "official_domain": "cdri.res.in",
        "career_url": "https://cdri.res.in/career.php",
        "recruitment_url": "https://cdri.res.in/career.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Centre for Cellular and Molecular Biology (CSIR-CCMB)": {
        "organisation_name": "CSIR - Centre for Cellular and Molecular Biology (CSIR-CCMB)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Telangana",
        "official_domain": "ccmb.res.in",
        "career_url": "https://www.ccmb.res.in/Careers/Opportunities",
        "recruitment_url": "https://www.ccmb.res.in/Careers/Opportunities",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Institute of Genomics and Integrative Biology (CSIR-IGIB)": {
        "organisation_name": "CSIR - Institute of Genomics and Integrative Biology (CSIR-IGIB)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Delhi",
        "official_domain": "igib.res.in",
        "career_url": "https://www.igib.res.in/career",
        "recruitment_url": "https://www.igib.res.in/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Indian Institute of Chemical Technology (CSIR-IICT)": {
        "organisation_name": "CSIR - Indian Institute of Chemical Technology (CSIR-IICT)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Telangana",
        "official_domain": "iict.res.in",
        "career_url": "https://www.iict.res.in/careers",
        "recruitment_url": "https://www.iict.res.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Food Technological Research Institute (CSIR-CFTRI)": {
        "organisation_name": "CSIR - Central Food Technological Research Institute (CSIR-CFTRI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Karnataka",
        "official_domain": "cftri.res.in",
        "career_url": "https://cftri.res.in/career",
        "recruitment_url": "https://cftri.res.in/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Electrochemical Research Institute (CSIR-CECRI)": {
        "organisation_name": "CSIR - Central Electrochemical Research Institute (CSIR-CECRI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Tamil Nadu",
        "official_domain": "cecri.res.in",
        "career_url": "https://www.cecri.res.in/Opportunities.aspx",
        "recruitment_url": "https://www.cecri.res.in/Opportunities.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Road Research Institute (CSIR-CRRI)": {
        "organisation_name": "CSIR - Central Road Research Institute (CSIR-CRRI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Delhi",
        "official_domain": "crridom.gov.in",
        "career_url": "https://crridom.gov.in/recruitment",
        "recruitment_url": "https://crridom.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Scientific Instruments Organisation (CSIR-CSIO)": {
        "organisation_name": "CSIR - Central Scientific Instruments Organisation (CSIR-CSIO)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Chandigarh",
        "official_domain": "csio.res.in",
        "career_url": "https://www.csio.res.in/recruitments.php",
        "recruitment_url": "https://www.csio.res.in/recruitments.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - National Environmental Engineering Research Institute (CSIR-NEERI)": {
        "organisation_name": "CSIR - National Environmental Engineering Research Institute (CSIR-NEERI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Maharashtra",
        "official_domain": "neeri.res.in",
        "career_url": "https://www.neeri.res.in/career/index",
        "recruitment_url": "https://www.neeri.res.in/career/index",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - National Aerospace Laboratories (CSIR-NAL)": {
        "organisation_name": "CSIR - National Aerospace Laboratories (CSIR-NAL)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Karnataka",
        "official_domain": "nal.res.in",
        "career_url": "https://www.nal.res.in/en/careers",
        "recruitment_url": "https://www.nal.res.in/en/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - National Institute of Oceanography (CSIR-NIO)": {
        "organisation_name": "CSIR - National Institute of Oceanography (CSIR-NIO)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Goa",
        "official_domain": "nio.res.in",
        "career_url": "https://www.nio.res.in/vacancies",
        "recruitment_url": "https://www.nio.res.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Building Research Institute (CSIR-CBRI)": {
        "organisation_name": "CSIR - Central Building Research Institute (CSIR-CBRI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Uttarakhand",
        "official_domain": "cbri.res.in",
        "career_url": "https://cbri.res.in/career/",
        "recruitment_url": "https://cbri.res.in/career/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Institute of Medicinal and Aromatic Plants (CSIR-CIMAP)": {
        "organisation_name": "CSIR - Central Institute of Medicinal and Aromatic Plants (CSIR-CIMAP)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Uttar Pradesh",
        "official_domain": "cimap.res.in",
        "career_url": "https://www.cimap.res.in/career",
        "recruitment_url": "https://www.cimap.res.in/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Institute of Himalayan Bioresource Technology (CSIR-IHBT)": {
        "organisation_name": "CSIR - Institute of Himalayan Bioresource Technology (CSIR-IHBT)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Himachal Pradesh",
        "official_domain": "ihbt.res.in",
        "career_url": "https://www.ihbt.res.in/en/recruitments",
        "recruitment_url": "https://www.ihbt.res.in/en/recruitments",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Structural Engineering Research Centre (CSIR-SERC)": {
        "organisation_name": "CSIR - Structural Engineering Research Centre (CSIR-SERC)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Tamil Nadu",
        "official_domain": "serc.res.in",
        "career_url": "https://serc.res.in/recruitment",
        "recruitment_url": "https://serc.res.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Advanced Materials and Processes Research Institute (CSIR-AMPRI)": {
        "organisation_name": "CSIR - Advanced Materials and Processes Research Institute (CSIR-AMPRI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Madhya Pradesh",
        "official_domain": "ampri.res.in",
        "career_url": "https://ampri.res.in/en/career/",
        "recruitment_url": "https://ampri.res.in/en/career/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - National Botanical Research Institute (CSIR-NBRI)": {
        "organisation_name": "CSIR - National Botanical Research Institute (CSIR-NBRI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Uttar Pradesh",
        "official_domain": "nbri.res.in",
        "career_url": "https://nbri.res.in/career.php",
        "recruitment_url": "https://nbri.res.in/career.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Institute of Microbial Technology (CSIR-IMTECH)": {
        "organisation_name": "CSIR - Institute of Microbial Technology (CSIR-IMTECH)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Chandigarh",
        "official_domain": "imtech.res.in",
        "career_url": "https://www.imtech.res.in/recruitments",
        "recruitment_url": "https://www.imtech.res.in/recruitments",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Institute of Mining and Fuel Research (CSIR-CIMFR)": {
        "organisation_name": "CSIR - Central Institute of Mining and Fuel Research (CSIR-CIMFR)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Jharkhand",
        "official_domain": "cimfr.nic.in",
        "career_url": "https://cimfr.nic.in/career.html",
        "recruitment_url": "https://cimfr.nic.in/career.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - National Institute for Interdisciplinary Science and Technology (CSIR-NIIST)": {
        "organisation_name": "CSIR - National Institute for Interdisciplinary Science and Technology (CSIR-NIIST)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Kerala",
        "official_domain": "niist.res.in",
        "career_url": "https://www.niist.res.in/opportunities",
        "recruitment_url": "https://www.niist.res.in/opportunities",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Indian Institute of Chemical Biology (CSIR-IICB)": {
        "organisation_name": "CSIR - Indian Institute of Chemical Biology (CSIR-IICB)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "West Bengal",
        "official_domain": "iicb.res.in",
        "career_url": "https://iicb.res.in/vacancies",
        "recruitment_url": "https://iicb.res.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Glass and Ceramic Research Institute (CSIR-CGCRI)": {
        "organisation_name": "CSIR - Central Glass and Ceramic Research Institute (CSIR-CGCRI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "West Bengal",
        "official_domain": "cgcri.res.in",
        "career_url": "https://www.cgcri.res.in/career-opportunity/",
        "recruitment_url": "https://www.cgcri.res.in/career-opportunity/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Institute of Minerals and Materials Technology (CSIR-IMMT)": {
        "organisation_name": "CSIR - Institute of Minerals and Materials Technology (CSIR-IMMT)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Odisha",
        "official_domain": "immt.res.in",
        "career_url": "https://www.immt.res.in/career",
        "recruitment_url": "https://www.immt.res.in/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - North East Institute of Science and Technology (CSIR-NEIST)": {
        "organisation_name": "CSIR - North East Institute of Science and Technology (CSIR-NEIST)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Assam",
        "official_domain": "neist.res.in",
        "career_url": "https://www.neist.res.in/career/",
        "recruitment_url": "https://www.neist.res.in/career/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - National Metallurgical Laboratory (CSIR-NML)": {
        "organisation_name": "CSIR - National Metallurgical Laboratory (CSIR-NML)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Jharkhand",
        "official_domain": "nmlindia.org",
        "career_url": "https://www.nmlindia.org/careers",
        "recruitment_url": "https://www.nmlindia.org/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Electronics Engineering Research Institute (CSIR-CEERI)": {
        "organisation_name": "CSIR - Central Electronics Engineering Research Institute (CSIR-CEERI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Rajasthan",
        "official_domain": "ceeri.res.in",
        "career_url": "https://www.ceeri.res.in/recruitments/",
        "recruitment_url": "https://www.ceeri.res.in/recruitments/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Mechanical Engineering Research Institute (CSIR-CMERI)": {
        "organisation_name": "CSIR - Central Mechanical Engineering Research Institute (CSIR-CMERI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "West Bengal",
        "official_domain": "cmeri.res.in",
        "career_url": "https://www.cmeri.res.in/career",
        "recruitment_url": "https://www.cmeri.res.in/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Leather Research Institute (CSIR-CLRI)": {
        "organisation_name": "CSIR - Central Leather Research Institute (CSIR-CLRI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Tamil Nadu",
        "official_domain": "clri.org",
        "career_url": "https://clri.org/Careers.aspx",
        "recruitment_url": "https://clri.org/Careers.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Indian Institute of Petroleum (CSIR-IIP)": {
        "organisation_name": "CSIR - Indian Institute of Petroleum (CSIR-IIP)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Uttarakhand",
        "official_domain": "iip.res.in",
        "career_url": "https://www.iip.res.in/notices/recruitment/",
        "recruitment_url": "https://www.iip.res.in/notices/recruitment/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "CSIR - Central Salt and Marine Chemicals Research Institute (CSIR-CSMCRI)": {
        "organisation_name": "CSIR - Central Salt and Marine Chemicals Research Institute (CSIR-CSMCRI)",
        "parent_organisation": "Council of Scientific and Industrial Research (CSIR)",
        "state": "Gujarat",
        "official_domain": "csmcri.res.in",
        "career_url": "https://www.csmcri.res.in/opportunities",
        "recruitment_url": "https://www.csmcri.res.in/opportunities",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # ICMR NATIONAL INSTITUTES (Key Institutes)
    # =========================================================================
    "ICMR - National Institute of Virology (ICMR-NIV)": {
        "organisation_name": "ICMR - National Institute of Virology (ICMR-NIV)",
        "parent_organisation": "Indian Council of Medical Research (ICMR)",
        "state": "Maharashtra",
        "official_domain": "niv.icmr.org.in",
        "career_url": "https://niv.icmr.org.in/career",
        "recruitment_url": "https://niv.icmr.org.in/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICMR - National Institute of Nutrition (ICMR-NIN)": {
        "organisation_name": "ICMR - National Institute of Nutrition (ICMR-NIN)",
        "parent_organisation": "Indian Council of Medical Research (ICMR)",
        "state": "Telangana",
        "official_domain": "nin.res.in",
        "career_url": "https://www.nin.res.in/employment.html",
        "recruitment_url": "https://www.nin.res.in/employment.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICMR - National Institute of Epidemiology (ICMR-NIE)": {
        "organisation_name": "ICMR - National Institute of Epidemiology (ICMR-NIE)",
        "parent_organisation": "Indian Council of Medical Research (ICMR)",
        "state": "Tamil Nadu",
        "official_domain": "nie.gov.in",
        "career_url": "https://nie.gov.in/careers.php",
        "recruitment_url": "https://nie.gov.in/careers.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICMR - National Institute of Cholera and Enteric Diseases (ICMR-NICED)": {
        "organisation_name": "ICMR - National Institute of Cholera and Enteric Diseases (ICMR-NICED)",
        "parent_organisation": "Indian Council of Medical Research (ICMR)",
        "state": "West Bengal",
        "official_domain": "niced.org.in",
        "career_url": "http://www.niced.org.in/noticepage.htm",
        "recruitment_url": "http://www.niced.org.in/noticepage.htm",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICMR - National Institute for Research in Reproductive and Child Health (ICMR-NIRRCH)": {
        "organisation_name": "ICMR - National Institute for Research in Reproductive and Child Health (ICMR-NIRRCH)",
        "parent_organisation": "Indian Council of Medical Research (ICMR)",
        "state": "Maharashtra",
        "official_domain": "nirrch.res.in",
        "career_url": "https://nirrch.res.in/careers/",
        "recruitment_url": "https://nirrch.res.in/careers/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICMR - National Institute for Research in Tuberculosis (ICMR-NIRT)": {
        "organisation_name": "ICMR - National Institute for Research in Tuberculosis (ICMR-NIRT)",
        "parent_organisation": "Indian Council of Medical Research (ICMR)",
        "state": "Tamil Nadu",
        "official_domain": "nirt.res.in",
        "career_url": "https://www.nirt.res.in/html/recruitment.htm",
        "recruitment_url": "https://www.nirt.res.in/html/recruitment.htm",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICMR - National Institute of Cancer Prevention and Research (ICMR-NICPR)": {
        "organisation_name": "ICMR - National Institute of Cancer Prevention and Research (ICMR-NICPR)",
        "parent_organisation": "Indian Council of Medical Research (ICMR)",
        "state": "Uttar Pradesh",
        "official_domain": "nicpr.icmr.org.in",
        "career_url": "https://nicpr.icmr.org.in/recruitment/",
        "recruitment_url": "https://nicpr.icmr.org.in/recruitment/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # ICAR NATIONAL RESEARCH INSTITUTES
    # =========================================================================
    "ICAR - Indian Agricultural Research Institute (ICAR-IARI)": {
        "organisation_name": "ICAR - Indian Agricultural Research Institute (ICAR-IARI)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Delhi",
        "official_domain": "iari.res.in",
        "career_url": "https://www.iari.res.in/index.php/en/announcements/jobs",
        "recruitment_url": "https://www.iari.res.in/index.php/en/announcements/jobs",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - Indian Veterinary Research Institute (ICAR-IVRI)": {
        "organisation_name": "ICAR - Indian Veterinary Research Institute (ICAR-IVRI)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Uttar Pradesh",
        "official_domain": "ivri.nic.in",
        "career_url": "https://ivri.nic.in/employment.aspx",
        "recruitment_url": "https://ivri.nic.in/employment.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - National Dairy Research Institute (ICAR-NDRI)": {
        "organisation_name": "ICAR - National Dairy Research Institute (ICAR-NDRI)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Haryana",
        "official_domain": "ndri.res.in",
        "career_url": "https://ndri.res.in/employment/",
        "recruitment_url": "https://ndri.res.in/employment/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - Central Institute of Fisheries Education (ICAR-CIFE)": {
        "organisation_name": "ICAR - Central Institute of Fisheries Education (ICAR-CIFE)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Maharashtra",
        "official_domain": "cife.edu.in",
        "career_url": "https://www.cife.edu.in/careers.html",
        "recruitment_url": "https://www.cife.edu.in/careers.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - National Academy of Agricultural Research Management (ICAR-NAARM)": {
        "organisation_name": "ICAR - National Academy of Agricultural Research Management (ICAR-NAARM)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Telangana",
        "official_domain": "naarm.org.in",
        "career_url": "https://naarm.org.in/jobs/",
        "recruitment_url": "https://naarm.org.in/jobs/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # PREMIER ENGINEERING INSTITUTES (IITs & NITs)
    # =========================================================================
    "Indian Institute of Technology Roorkee (IIT Roorkee)": {
        "organisation_name": "Indian Institute of Technology Roorkee (IIT Roorkee)",
        "state": "Uttarakhand",
        "official_domain": "iitr.ac.in",
        "career_url": "https://www.iitr.ac.in/careers",
        "recruitment_url": "https://www.iitr.ac.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology Guwahati (IIT Guwahati)": {
        "organisation_name": "Indian Institute of Technology Guwahati (IIT Guwahati)",
        "state": "Assam",
        "official_domain": "iitg.ac.in",
        "career_url": "https://www.iitg.ac.in/recruitment/",
        "recruitment_url": "https://www.iitg.ac.in/recruitment/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology Hyderabad (IIT Hyderabad)": {
        "organisation_name": "Indian Institute of Technology Hyderabad (IIT Hyderabad)",
        "state": "Telangana",
        "official_domain": "iith.ac.in",
        "career_url": "https://www.iith.ac.in/careers/",
        "recruitment_url": "https://www.iith.ac.in/careers/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology Indore (IIT Indore)": {
        "organisation_name": "Indian Institute of Technology Indore (IIT Indore)",
        "state": "Madhya Pradesh",
        "official_domain": "iiti.ac.in",
        "career_url": "https://www.iiti.ac.in/careers",
        "recruitment_url": "https://www.iiti.ac.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology (BHU) Varanasi": {
        "organisation_name": "Indian Institute of Technology (BHU) Varanasi",
        "state": "Uttar Pradesh",
        "official_domain": "iitbhu.ac.in",
        "career_url": "https://www.iitbhu.ac.in/job",
        "recruitment_url": "https://www.iitbhu.ac.in/job",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology (ISM) Dhanbad": {
        "organisation_name": "Indian Institute of Technology (ISM) Dhanbad",
        "state": "Jharkhand",
        "official_domain": "iitism.ac.in",
        "career_url": "https://www.iitism.ac.in/career",
        "recruitment_url": "https://www.iitism.ac.in/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology Gandhinagar (IIT Gandhinagar)": {
        "organisation_name": "Indian Institute of Technology Gandhinagar (IIT Gandhinagar)",
        "state": "Gujarat",
        "official_domain": "iitgn.ac.in",
        "career_url": "https://iitgn.ac.in/careers",
        "recruitment_url": "https://iitgn.ac.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology Patna (IIT Patna)": {
        "organisation_name": "Indian Institute of Technology Patna (IIT Patna)",
        "state": "Bihar",
        "official_domain": "iitp.ac.in",
        "career_url": "https://www.iitp.ac.in/job-opportunity",
        "recruitment_url": "https://www.iitp.ac.in/job-opportunity",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology Bhubaneswar (IIT Bhubaneswar)": {
        "organisation_name": "Indian Institute of Technology Bhubaneswar (IIT Bhubaneswar)",
        "state": "Odisha",
        "official_domain": "iitbbs.ac.in",
        "career_url": "https://www.iitbbs.ac.in/jobs.php",
        "recruitment_url": "https://www.iitbbs.ac.in/jobs.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology Mandi (IIT Mandi)": {
        "organisation_name": "Indian Institute of Technology Mandi (IIT Mandi)",
        "state": "Himachal Pradesh",
        "official_domain": "iitmandi.ac.in",
        "career_url": "https://www.iitmandi.ac.in/careers",
        "recruitment_url": "https://www.iitmandi.ac.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology Ropar (IIT Ropar)": {
        "organisation_name": "Indian Institute of Technology Ropar (IIT Ropar)",
        "state": "Punjab",
        "official_domain": "iitrpr.ac.in",
        "career_url": "https://www.iitrpr.ac.in/jobs",
        "recruitment_url": "https://www.iitrpr.ac.in/jobs",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Institute of Technology Tiruchirappalli (NIT Trichy)": {
        "organisation_name": "National Institute of Technology Tiruchirappalli (NIT Trichy)",
        "state": "Tamil Nadu",
        "official_domain": "nitt.edu",
        "career_url": "https://www.nitt.edu/home/other/jobs/",
        "recruitment_url": "https://www.nitt.edu/home/other/jobs/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Institute of Technology Karnataka (NIT Surathkal)": {
        "organisation_name": "National Institute of Technology Karnataka (NIT Surathkal)",
        "state": "Karnataka",
        "official_domain": "nitk.ac.in",
        "career_url": "https://www.nitk.ac.in/recruitment",
        "recruitment_url": "https://www.nitk.ac.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Institute of Technology Warangal (NIT Warangal)": {
        "organisation_name": "National Institute of Technology Warangal (NIT Warangal)",
        "state": "Telangana",
        "official_domain": "nitw.ac.in",
        "career_url": "https://www.nitw.ac.in/careers",
        "recruitment_url": "https://www.nitw.ac.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Institute of Technology Rourkela (NIT Rourkela)": {
        "organisation_name": "National Institute of Technology Rourkela (NIT Rourkela)",
        "state": "Odisha",
        "official_domain": "nitrkl.ac.in",
        "career_url": "https://www.nitrkl.ac.in/Career",
        "recruitment_url": "https://www.nitrkl.ac.in/Career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Institute of Technology Calicut (NIT Calicut)": {
        "organisation_name": "National Institute of Technology Calicut (NIT Calicut)",
        "state": "Kerala",
        "official_domain": "nitc.ac.in",
        "career_url": "https://www.nitc.ac.in/careers",
        "recruitment_url": "https://www.nitc.ac.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Motilal Nehru National Institute of Technology (MNNIT Allahabad)": {
        "organisation_name": "Motilal Nehru National Institute of Technology (MNNIT Allahabad)",
        "state": "Uttar Pradesh",
        "official_domain": "mnnit.ac.in",
        "career_url": "https://www.mnnit.ac.in/index.php/jobs",
        "recruitment_url": "https://www.mnnit.ac.in/index.php/jobs",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Malaviya National Institute of Technology Jaipur (MNIT Jaipur)": {
        "organisation_name": "Malaviya National Institute of Technology Jaipur (MNIT Jaipur)",
        "state": "Rajasthan",
        "official_domain": "mnit.ac.in",
        "career_url": "https://www.mnit.ac.in/careers",
        "recruitment_url": "https://www.mnit.ac.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Visvesvaraya National Institute of Technology (VNIT Nagpur)": {
        "organisation_name": "Visvesvaraya National Institute of Technology (VNIT Nagpur)",
        "state": "Maharashtra",
        "official_domain": "vnit.ac.in",
        "career_url": "https://vnit.ac.in/index.php/recruitment/",
        "recruitment_url": "https://vnit.ac.in/index.php/recruitment/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Maulana Azad National Institute of Technology (MANIT Bhopal)": {
        "organisation_name": "Maulana Azad National Institute of Technology (MANIT Bhopal)",
        "state": "Madhya Pradesh",
        "official_domain": "manit.ac.in",
        "career_url": "https://www.manit.ac.in/recruitment",
        "recruitment_url": "https://www.manit.ac.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Sardar Vallabhbhai National Institute of Technology (SVNIT Surat)": {
        "organisation_name": "Sardar Vallabhbhai National Institute of Technology (SVNIT Surat)",
        "state": "Gujarat",
        "official_domain": "svnit.ac.in",
        "career_url": "https://www.svnit.ac.in/web/recruitment.php",
        "recruitment_url": "https://www.svnit.ac.in/web/recruitment.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # AIIMS INSTITUTES
    # =========================================================================
    "All India Institute of Medical Sciences, New Delhi (AIIMS New Delhi)": {
        "organisation_name": "All India Institute of Medical Sciences, New Delhi (AIIMS New Delhi)",
        "state": "Delhi",
        "official_domain": "aiims.edu",
        "career_url": "https://www.aiims.edu/en/notices/recruitment.html",
        "recruitment_url": "https://www.aiims.edu/en/notices/recruitment.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "All India Institute of Medical Sciences, Bhopal (AIIMS Bhopal)": {
        "organisation_name": "All India Institute of Medical Sciences, Bhopal (AIIMS Bhopal)",
        "state": "Madhya Pradesh",
        "official_domain": "aiimsbhopal.edu.in",
        "career_url": "https://aiimsbhopal.edu.in/index_controller/vacancies",
        "recruitment_url": "https://aiimsbhopal.edu.in/index_controller/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "All India Institute of Medical Sciences, Bhubaneswar (AIIMS Bhubaneswar)": {
        "organisation_name": "All India Institute of Medical Sciences, Bhubaneswar (AIIMS Bhubaneswar)",
        "state": "Odisha",
        "official_domain": "aiimsbhubaneswar.nic.in",
        "career_url": "https://aiimsbhubaneswar.nic.in/recruitment.aspx",
        "recruitment_url": "https://aiimsbhubaneswar.nic.in/recruitment.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "All India Institute of Medical Sciences, Jodhpur (AIIMS Jodhpur)": {
        "organisation_name": "All India Institute of Medical Sciences, Jodhpur (AIIMS Jodhpur)",
        "state": "Rajasthan",
        "official_domain": "aiimsjodhpur.edu.in",
        "career_url": "https://www.aiimsjodhpur.edu.in/recruitment.php",
        "recruitment_url": "https://www.aiimsjodhpur.edu.in/recruitment.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "All India Institute of Medical Sciences, Patna (AIIMS Patna)": {
        "organisation_name": "All India Institute of Medical Sciences, Patna (AIIMS Patna)",
        "state": "Bihar",
        "official_domain": "aiimspatna.edu.in",
        "career_url": "https://aiimspatna.edu.in/recruitment.php",
        "recruitment_url": "https://aiimspatna.edu.in/recruitment.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "All India Institute of Medical Sciences, Rishikesh (AIIMS Rishikesh)": {
        "organisation_name": "All India Institute of Medical Sciences, Rishikesh (AIIMS Rishikesh)",
        "state": "Uttarakhand",
        "official_domain": "aiimsrishikesh.edu.in",
        "career_url": "https://aiimsrishikesh.edu.in/a1_1/vacancies.php",
        "recruitment_url": "https://aiimsrishikesh.edu.in/a1_1/vacancies.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "All India Institute of Medical Sciences, Raipur (AIIMS Raipur)": {
        "organisation_name": "All India Institute of Medical Sciences, Raipur (AIIMS Raipur)",
        "state": "Chhattisgarh",
        "official_domain": "aiimsraipur.edu.in",
        "career_url": "https://www.aiimsraipur.edu.in/user/vacancies.php",
        "recruitment_url": "https://www.aiimsraipur.edu.in/user/vacancies.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "All India Institute of Medical Sciences, Nagpur (AIIMS Nagpur)": {
        "organisation_name": "All India Institute of Medical Sciences, Nagpur (AIIMS Nagpur)",
        "state": "Maharashtra",
        "official_domain": "aiimsnagpur.edu.in",
        "career_url": "https://aiimsnagpur.edu.in/recruitment_notices",
        "recruitment_url": "https://aiimsnagpur.edu.in/recruitment_notices",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "All India Institute of Medical Sciences, Kalyani (AIIMS Kalyani)": {
        "organisation_name": "All India Institute of Medical Sciences, Kalyani (AIIMS Kalyani)",
        "state": "West Bengal",
        "official_domain": "aiimskalyani.edu.in",
        "career_url": "https://aiimskalyani.edu.in/recruitment/",
        "recruitment_url": "https://aiimskalyani.edu.in/recruitment/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # CENTRAL UNIVERSITIES
    # =========================================================================
    "Jawaharlal Nehru University (JNU)": {
        "organisation_name": "Jawaharlal Nehru University (JNU)",
        "state": "Delhi",
        "official_domain": "jnu.ac.in",
        "career_url": "https://www.jnu.ac.in/career",
        "recruitment_url": "https://www.jnu.ac.in/career",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "University of Delhi (DU)": {
        "organisation_name": "University of Delhi (DU)",
        "state": "Delhi",
        "official_domain": "du.ac.in",
        "career_url": "https://www.du.ac.in/index.php?page=work-with-du",
        "recruitment_url": "https://www.du.ac.in/index.php?page=work-with-du",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Banaras Hindu University (BHU)": {
        "organisation_name": "Banaras Hindu University (BHU)",
        "state": "Uttar Pradesh",
        "official_domain": "bhu.ac.in",
        "career_url": "https://www.bhu.ac.in/Site/Recruitments/",
        "recruitment_url": "https://www.bhu.ac.in/Site/Recruitments/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Aligarh Muslim University (AMU)": {
        "organisation_name": "Aligarh Muslim University (AMU)",
        "state": "Uttar Pradesh",
        "official_domain": "amu.ac.in",
        "career_url": "https://www.amu.ac.in/career.jsp",
        "recruitment_url": "https://www.amu.ac.in/career.jsp",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "University of Hyderabad (UoH)": {
        "organisation_name": "University of Hyderabad (UoH)",
        "state": "Telangana",
        "official_domain": "uohyd.ac.in",
        "career_url": "https://uohyd.ac.in/careers-uoh/",
        "recruitment_url": "https://uohyd.ac.in/careers-uoh/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Jamia Millia Islamia (JMI)": {
        "organisation_name": "Jamia Millia Islamia (JMI)",
        "state": "Delhi",
        "official_domain": "jmi.ac.in",
        "career_url": "https://www.jmi.ac.in/bulletinboard/Jobs",
        "recruitment_url": "https://www.jmi.ac.in/bulletinboard/Jobs",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Visva-Bharati University": {
        "organisation_name": "Visva-Bharati University",
        "state": "West Bengal",
        "official_domain": "visvabharati.ac.in",
        "career_url": "https://visvabharati.ac.in/Appointments.html",
        "recruitment_url": "https://visvabharati.ac.in/Appointments.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Pondicherry University": {
        "organisation_name": "Pondicherry University",
        "state": "Puducherry",
        "official_domain": "pondiuni.edu.in",
        "career_url": "https://www.pondiuni.edu.in/careers/",
        "recruitment_url": "https://www.pondiuni.edu.in/careers/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Tezpur University": {
        "organisation_name": "Tezpur University",
        "state": "Assam",
        "official_domain": "tezu.ernet.in",
        "career_url": "http://www.tezu.ernet.in/orders.htm",
        "recruitment_url": "http://www.tezu.ernet.in/orders.htm",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # ADDITIONAL IITs & NITs
    # =========================================================================
    "Indian Institute of Technology Kharagpur (IIT Kharagpur)": {
        "organisation_name": "Indian Institute of Technology Kharagpur (IIT Kharagpur)",
        "state": "West Bengal",
        "official_domain": "iitkgp.ac.in",
        "career_url": "https://www.iitkgp.ac.in/careers",
        "recruitment_url": "https://www.iitkgp.ac.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology Kanpur (IIT Kanpur)": {
        "organisation_name": "Indian Institute of Technology Kanpur (IIT Kanpur)",
        "state": "Uttar Pradesh",
        "official_domain": "iitk.ac.in",
        "career_url": "https://www.iitk.ac.in/dofa/vacancies",
        "recruitment_url": "https://www.iitk.ac.in/dofa/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Technology Palakkad (IIT Palakkad)": {
        "organisation_name": "Indian Institute of Technology Palakkad (IIT Palakkad)",
        "state": "Kerala",
        "official_domain": "iitpkd.ac.in",
        "career_url": "https://iitpkd.ac.in/careers",
        "recruitment_url": "https://iitpkd.ac.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Institute of Technology Jalandhar (NIT Jalandhar)": {
        "organisation_name": "National Institute of Technology Jalandhar (NIT Jalandhar)",
        "state": "Punjab",
        "official_domain": "nitj.ac.in",
        "career_url": "https://www.nitj.ac.in/jobs",
        "recruitment_url": "https://www.nitj.ac.in/jobs",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Institute of Technology Goa (NIT Goa)": {
        "organisation_name": "National Institute of Technology Goa (NIT Goa)",
        "state": "Goa",
        "official_domain": "nitgoa.ac.in",
        "career_url": "https://www.nitgoa.ac.in/recruitment",
        "recruitment_url": "https://www.nitgoa.ac.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # AUTONOMOUS S&T RESEARCH INSTITUTES (DST, DBT, DAE, DOS)
    # =========================================================================
    "Aryabhatta Research Institute of Observational Sciences (ARIES)": {
        "organisation_name": "Aryabhatta Research Institute of Observational Sciences (ARIES)",
        "parent_organisation": "Department of Science and Technology (DST)",
        "state": "Uttarakhand",
        "official_domain": "aries.res.in",
        "career_url": "https://www.aries.res.in/recruitments",
        "recruitment_url": "https://www.aries.res.in/recruitments",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Raman Research Institute (RRI)": {
        "organisation_name": "Raman Research Institute (RRI)",
        "parent_organisation": "Department of Science and Technology (DST)",
        "state": "Karnataka",
        "official_domain": "rri.res.in",
        "career_url": "https://www.rri.res.in/careers",
        "recruitment_url": "https://www.rri.res.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Brain Research Centre (NBRC)": {
        "organisation_name": "National Brain Research Centre (NBRC)",
        "parent_organisation": "Department of Biotechnology (DBT)",
        "state": "Haryana",
        "official_domain": "nbrc.ac.in",
        "career_url": "http://www.nbrc.ac.in/newweb/careers",
        "recruitment_url": "http://www.nbrc.ac.in/newweb/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Atmospheric Research Laboratory (NARL)": {
        "organisation_name": "National Atmospheric Research Laboratory (NARL)",
        "parent_organisation": "Department of Space (DOS)",
        "state": "Andhra Pradesh",
        "official_domain": "narl.gov.in",
        "career_url": "https://www.narl.gov.in/?q=careers",
        "recruitment_url": "https://www.narl.gov.in/?q=careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ISRO Propulsion Complex (IPRC)": {
        "organisation_name": "ISRO Propulsion Complex (IPRC)",
        "parent_organisation": "Indian Space Research Organisation (ISRO)",
        "state": "Tamil Nadu",
        "official_domain": "iprc.gov.in",
        "career_url": "https://www.iprc.gov.in/career.html",
        "recruitment_url": "https://www.iprc.gov.in/career.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Centre for Railway Information Systems (CRIS)": {
        "organisation_name": "Centre for Railway Information Systems (CRIS)",
        "parent_organisation": "Ministry of Railways",
        "state": "Delhi",
        "official_domain": "cris.org.in",
        "career_url": "https://cris.org.in/crisweb/design1/Careers.jsp",
        "recruitment_url": "https://cris.org.in/crisweb/design1/Careers.jsp",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Insurance Regulatory and Development Authority of India (IRDAI)": {
        "organisation_name": "Insurance Regulatory and Development Authority of India (IRDAI)",
        "state": "Telangana",
        "official_domain": "irdai.gov.in",
        "career_url": "https://irdai.gov.in/employment-opportunities",
        "recruitment_url": "https://irdai.gov.in/employment-opportunities",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },

    # =========================================================================
    # ICAR SPECIALIZED INSTITUTES
    # =========================================================================
    "ICAR - Central Inland Fisheries Research Institute (ICAR-CIFRI)": {
        "organisation_name": "ICAR - Central Inland Fisheries Research Institute (ICAR-CIFRI)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "West Bengal",
        "official_domain": "cifri.res.in",
        "career_url": "http://www.cifri.res.in/job.html",
        "recruitment_url": "http://www.cifri.res.in/job.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - Central Institute of Research on Cotton Technology (ICAR-CIRCOT)": {
        "organisation_name": "ICAR - Central Institute of Research on Cotton Technology (ICAR-CIRCOT)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Maharashtra",
        "official_domain": "circot.icar.gov.in",
        "career_url": "https://circot.icar.gov.in/en/job-opportunities/",
        "recruitment_url": "https://circot.icar.gov.in/en/job-opportunities/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - National Bureau of Animal Genetic Resources (ICAR-NBAGR)": {
        "organisation_name": "ICAR - National Bureau of Animal Genetic Resources (ICAR-NBAGR)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Haryana",
        "official_domain": "nbagr.icar.gov.in",
        "career_url": "http://nbagr.icar.gov.in/vacancies/",
        "recruitment_url": "http://nbagr.icar.gov.in/vacancies/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - National Research Centre on Orchids (ICAR-NRCO)": {
        "organisation_name": "ICAR - National Research Centre on Orchids (ICAR-NRCO)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Sikkim",
        "official_domain": "nrco.icar.gov.in",
        "career_url": "https://nrco.icar.gov.in/recruitment",
        "recruitment_url": "https://nrco.icar.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - Central Sheep and Wool Research Institute (ICAR-CSWRI)": {
        "organisation_name": "ICAR - Central Sheep and Wool Research Institute (ICAR-CSWRI)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Rajasthan",
        "official_domain": "cswri.icar.gov.in",
        "career_url": "https://cswri.icar.gov.in/job_opportunities.asp",
        "recruitment_url": "https://cswri.icar.gov.in/job_opportunities.asp",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    # =========================================================================
    # IIITs & REGIONAL NITs
    # =========================================================================
    "Indian Institute of Information Technology Allahabad (IIIT-A)": {
        "organisation_name": "Indian Institute of Information Technology Allahabad",
        "state": "Uttar Pradesh",
        "official_domain": "iiita.ac.in",
        "career_url": "https://www.iiita.ac.in/recruitment/",
        "recruitment_url": "https://www.iiita.ac.in/recruitment/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Information Technology Dharwad": {
        "organisation_name": "Indian Institute of Information Technology Dharwad",
        "state": "Karnataka",
        "official_domain": "iiitdwd.ac.in",
        "career_url": "https://iiitdwd.ac.in/Careers.php",
        "recruitment_url": "https://iiitdwd.ac.in/Careers.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Information Technology Kalyani": {
        "organisation_name": "Indian Institute of Information Technology Kalyani",
        "state": "West Bengal",
        "official_domain": "iiitkalyani.ac.in",
        "career_url": "http://iiitkalyani.ac.in/recruitment.html",
        "recruitment_url": "http://iiitkalyani.ac.in/recruitment.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Indian Institute of Information Technology Sri City": {
        "organisation_name": "Indian Institute of Information Technology Sri City",
        "state": "Andhra Pradesh",
        "official_domain": "iiits.ac.in",
        "career_url": "https://www.iiits.ac.in/careers/",
        "recruitment_url": "https://www.iiits.ac.in/careers/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "NIT Patna": {
        "organisation_name": "National Institute of Technology Patna",
        "state": "Bihar",
        "official_domain": "nitp.ac.in",
        "career_url": "https://www.nitp.ac.in/recruitment",
        "recruitment_url": "https://www.nitp.ac.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "NIT Silchar": {
        "organisation_name": "National Institute of Technology Silchar",
        "state": "Assam",
        "official_domain": "nits.ac.in",
        "career_url": "http://www.nits.ac.in/jobs/jobs.php",
        "recruitment_url": "http://www.nits.ac.in/jobs/jobs.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "NIT Arunachal Pradesh": {
        "organisation_name": "National Institute of Technology Arunachal Pradesh",
        "state": "Arunachal Pradesh",
        "official_domain": "nitap.ac.in",
        "career_url": "https://www.nitap.ac.in/recruitment",
        "recruitment_url": "https://www.nitap.ac.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "NIT Mizoram": {
        "organisation_name": "National Institute of Technology Mizoram",
        "state": "Mizoram",
        "official_domain": "nitmz.ac.in",
        "career_url": "https://www.nitmz.ac.in/recruitment",
        "recruitment_url": "https://www.nitmz.ac.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "NIT Raipur": {
        "organisation_name": "National Institute of Technology Raipur",
        "state": "Chhattisgarh",
        "official_domain": "nitrr.ac.in",
        "career_url": "http://www.nitrr.ac.in/recruitment.php",
        "recruitment_url": "http://www.nitrr.ac.in/recruitment.php",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Maulana Azad National Institute of Technology Bhopal (MANIT)": {
        "organisation_name": "Maulana Azad National Institute of Technology Bhopal",
        "state": "Madhya Pradesh",
        "official_domain": "manit.ac.in",
        "career_url": "https://www.manit.ac.in/recruitment",
        "recruitment_url": "https://www.manit.ac.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "IIT Jammu": {
        "organisation_name": "Indian Institute of Technology Jammu",
        "state": "Jammu and Kashmir",
        "official_domain": "iitjammu.ac.in",
        "career_url": "https://www.iitjammu.ac.in/jobs",
        "recruitment_url": "https://www.iitjammu.ac.in/jobs",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    # =========================================================================
    # CENTRAL UNIVERSITIES
    # =========================================================================
    "Central University of South Bihar": {
        "organisation_name": "Central University of South Bihar",
        "state": "Bihar",
        "official_domain": "cusb.ac.in",
        "career_url": "https://www.cusb.ac.in/recruitment/",
        "recruitment_url": "https://www.cusb.ac.in/recruitment/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Central University of Kashmir": {
        "organisation_name": "Central University of Kashmir",
        "state": "Jammu and Kashmir",
        "official_domain": "cukashmir.ac.in",
        "career_url": "https://www.cukashmir.ac.in/jobs.aspx",
        "recruitment_url": "https://www.cukashmir.ac.in/jobs.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Central University of Haryana": {
        "organisation_name": "Central University of Haryana",
        "state": "Haryana",
        "official_domain": "cuh.ac.in",
        "career_url": "https://www.cuh.ac.in/recruitment.aspx",
        "recruitment_url": "https://www.cuh.ac.in/recruitment.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Babasaheb Bhimrao Ambedkar University": {
        "organisation_name": "Babasaheb Bhimrao Ambedkar University",
        "state": "Uttar Pradesh",
        "official_domain": "bbau.ac.in",
        "career_url": "https://www.bbau.ac.in/recruitment.aspx",
        "recruitment_url": "https://www.bbau.ac.in/recruitment.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    # =========================================================================
    # ISRO CENTRES & UNITS
    # =========================================================================
    "Liquid Propulsion Systems Centre (LPSC)": {
        "organisation_name": "Liquid Propulsion Systems Centre (LPSC)",
        "parent_organisation": "Indian Space Research Organisation (ISRO)",
        "state": "Kerala",
        "official_domain": "lpsc.gov.in",
        "career_url": "https://www.lpsc.gov.in/recruitment.html",
        "recruitment_url": "https://www.lpsc.gov.in/recruitment.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Master Control Facility (MCF)": {
        "organisation_name": "Master Control Facility (MCF)",
        "parent_organisation": "Indian Space Research Organisation (ISRO)",
        "state": "Karnataka",
        "official_domain": "mcf.gov.in",
        "career_url": "https://www.mcf.gov.in/careers",
        "recruitment_url": "https://www.mcf.gov.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    # =========================================================================
    # DRDO LABORATORIES
    # =========================================================================
    "Institute of Nuclear Medicine & Allied Sciences (INMAS)": {
        "organisation_name": "Institute of Nuclear Medicine and Allied Sciences (INMAS)",
        "parent_organisation": "Defence Research and Development Organisation (DRDO)",
        "state": "Delhi",
        "official_domain": "drdo.gov.in",
        "career_url": "https://www.drdo.gov.in/drdo/careers",
        "recruitment_url": "https://www.drdo.gov.in/drdo/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Aeronautical Development Establishment (ADE)": {
        "organisation_name": "Aeronautical Development Establishment (ADE)",
        "parent_organisation": "Defence Research and Development Organisation (DRDO)",
        "state": "Karnataka",
        "official_domain": "drdo.gov.in",
        "career_url": "https://www.drdo.gov.in/drdo/careers",
        "recruitment_url": "https://www.drdo.gov.in/drdo/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Vehicle Research & Development Establishment (VRDE)": {
        "organisation_name": "Vehicle Research and Development Establishment (VRDE)",
        "parent_organisation": "Defence Research and Development Organisation (DRDO)",
        "state": "Maharashtra",
        "official_domain": "drdo.gov.in",
        "career_url": "https://www.drdo.gov.in/drdo/careers",
        "recruitment_url": "https://www.drdo.gov.in/drdo/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "High Energy Materials Research Laboratory (HEMRL)": {
        "organisation_name": "High Energy Materials Research Laboratory (HEMRL)",
        "parent_organisation": "Defence Research and Development Organisation (DRDO)",
        "state": "Maharashtra",
        "official_domain": "drdo.gov.in",
        "career_url": "https://www.drdo.gov.in/drdo/careers",
        "recruitment_url": "https://www.drdo.gov.in/drdo/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Centre for High Energy Systems & Sciences (CHESS)": {
        "organisation_name": "Centre for High Energy Systems and Sciences (CHESS)",
        "parent_organisation": "Defence Research and Development Organisation (DRDO)",
        "state": "Telangana",
        "official_domain": "drdo.gov.in",
        "career_url": "https://www.drdo.gov.in/drdo/careers",
        "recruitment_url": "https://www.drdo.gov.in/drdo/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    # =========================================================================
    # AUTONOMOUS S&T / AGRICULTURAL / MEDICAL INSTITUTES
    # =========================================================================
    "Indian Institute of Tropical Meteorology (IITM)": {
        "organisation_name": "Indian Institute of Tropical Meteorology (IITM)",
        "state": "Maharashtra",
        "official_domain": "tropmet.res.in",
        "career_url": "https://www.tropmet.res.in/Careers",
        "recruitment_url": "https://www.tropmet.res.in/Careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Institute of Nano Science and Technology (INST)": {
        "organisation_name": "Institute of Nano Science and Technology (INST)",
        "state": "Punjab",
        "official_domain": "inst.ac.in",
        "career_url": "https://inst.ac.in/careers",
        "recruitment_url": "https://inst.ac.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "S.N. Bose National Centre for Basic Sciences": {
        "organisation_name": "S.N. Bose National Centre for Basic Sciences",
        "state": "West Bengal",
        "official_domain": "bose.res.in",
        "career_url": "https://newweb.bose.res.in/recruitment/",
        "recruitment_url": "https://newweb.bose.res.in/recruitment/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "Agharkar Research Institute": {
        "organisation_name": "Agharkar Research Institute",
        "state": "Maharashtra",
        "official_domain": "aripune.org",
        "career_url": "http://aripune.org/career/",
        "recruitment_url": "http://aripune.org/career/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "International Advanced Research Centre for Powder Metallurgy and New Materials (ARCI)": {
        "organisation_name": "International Advanced Research Centre for Powder Metallurgy and New Materials (ARCI)",
        "state": "Telangana",
        "official_domain": "arci.res.in",
        "career_url": "https://www.arci.res.in/careers",
        "recruitment_url": "https://www.arci.res.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "North East Centre for Technology Application & Reach (NECTAR)": {
        "organisation_name": "North East Centre for Technology Application and Reach (NECTAR)",
        "state": "Meghalaya",
        "official_domain": "nectar.org.in",
        "career_url": "https://www.nectar.org.in/recruitment",
        "recruitment_url": "https://www.nectar.org.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "National Supercomputing Mission": {
        "organisation_name": "National Supercomputing Mission",
        "state": "Maharashtra",
        "official_domain": "nsmindia.in",
        "career_url": "https://nsmindia.in",
        "recruitment_url": "https://nsmindia.in",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - Research Complex for Eastern Region (RCER)": {
        "organisation_name": "ICAR - Research Complex for Eastern Region (RCER)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Bihar",
        "official_domain": "icarrcer.in",
        "career_url": "https://icarrcer.in/career/",
        "recruitment_url": "https://icarrcer.in/career/",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - Directorate of Mushroom Research (DMR)": {
        "organisation_name": "ICAR - Directorate of Mushroom Research (DMR)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Himachal Pradesh",
        "official_domain": "dmrsolan.icar.gov.in",
        "career_url": "https://dmrsolan.icar.gov.in/vacancies",
        "recruitment_url": "https://dmrsolan.icar.gov.in/vacancies",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - Sugarcane Breeding Institute (SBI)": {
        "organisation_name": "ICAR - Sugarcane Breeding Institute (SBI)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Tamil Nadu",
        "official_domain": "sugarcane.icar.gov.in",
        "career_url": "https://sugarcane.icar.gov.in/index.php/en/recruitment",
        "recruitment_url": "https://sugarcane.icar.gov.in/index.php/en/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - National Meat Research Institute (NMRI)": {
        "organisation_name": "ICAR - National Meat Research Institute (NMRI)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Telangana",
        "official_domain": "nmri.icar.gov.in",
        "career_url": "https://nmri.icar.gov.in/careers",
        "recruitment_url": "https://nmri.icar.gov.in/careers",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - National Institute on Foot and Mouth Disease (NIFMD)": {
        "organisation_name": "ICAR - National Institute on Foot and Mouth Disease (NIFMD)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "Odisha",
        "official_domain": "nifmd.icar.gov.in",
        "career_url": "https://nifmd.icar.gov.in/recruitment",
        "recruitment_url": "https://nifmd.icar.gov.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICAR - Central Research Institute for Jute & Allied Fibres (CRIJAF)": {
        "organisation_name": "ICAR - Central Research Institute for Jute and Allied Fibres (CRIJAF)",
        "parent_organisation": "Indian Council of Agricultural Research (ICAR)",
        "state": "West Bengal",
        "official_domain": "crijaf.icar.gov.in",
        "career_url": "http://crijaf.icar.gov.in/recruitment.html",
        "recruitment_url": "http://crijaf.icar.gov.in/recruitment.html",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICMR - Rajendra Memorial Research Institute of Medical Sciences": {
        "organisation_name": "ICMR - Rajendra Memorial Research Institute of Medical Sciences",
        "parent_organisation": "Indian Council of Medical Research (ICMR)",
        "state": "Bihar",
        "official_domain": "rmrims.org.in",
        "career_url": "http://rmrims.org.in/Career.aspx",
        "recruitment_url": "http://rmrims.org.in/Career.aspx",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
    "ICMR - National Institute for Research in Digital Health": {
        "organisation_name": "ICMR - National Institute for Research in Digital Health",
        "parent_organisation": "Indian Council of Medical Research (ICMR)",
        "state": "Delhi",
        "official_domain": "nirdh.icmr.org.in",
        "career_url": "https://nirdh.icmr.org.in/recruitment",
        "recruitment_url": "https://nirdh.icmr.org.in/recruitment",
        "source_type": "portal",
        "government_level": "central",
        "confidence_category": "AUTHORITATIVE",
    },
}
