"""
Job Operating System - Comprehensive Government Seed Registry
Covers:
- Central Government (Ministries, Departments, Attached Offices, Missions)
- All 28 States & 8 Union Territories
- Central & State PSUs / CPSEs
- Research & Academic Institutes (IITs, NITs, IIITs, IISERs, CSIR, ICMR, DRDO, ISRO)
- Regulators, Statutory Authorities, and Commissions
- Healthcare (AIIMS, NHM)
- Project & Contractual Missions
"""
from typing import List, Dict, Any

INDIAN_STATES = [
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
    "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka",
    "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram",
    "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu",
    "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
]

INDIAN_UTS = [
    "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry"
]

ALL_STATES = INDIAN_STATES
ALL_UTS = INDIAN_UTS

SEED_GOVERNMENT_ORGANISATIONS: List[Dict[str, Any]] = [
    # --- CENTRAL MINISTRIES & DEPARTMENTS ---
    {
        "organisation_name": "Ministry of Electronics and Information Technology (MeitY)",
        "organisation_type": "ministry",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "meity.gov.in",
        "career_url": "https://www.meity.gov.in/vacancies",
        "recruitment_url": "https://www.meity.gov.in/vacancies",
        "source_type": "portal",
    },
    {
        "organisation_name": "NITI Aayog (National Institution for Transforming India)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "niti.gov.in",
        "career_url": "https://www.niti.gov.in/career/work-with-niti",
        "recruitment_url": "https://www.niti.gov.in/career/vacancy-circulars",
        "source_type": "portal",
    },
    {
        "organisation_name": "Department of Science and Technology (DST)",
        "organisation_type": "department",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "dst.gov.in",
        "career_url": "https://dst.gov.in/recruitment",
        "recruitment_url": "https://dst.gov.in/recruitment",
        "source_type": "portal",
    },
    {
        "organisation_name": "Department of Biotechnology (DBT)",
        "organisation_type": "department",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "dbtindia.gov.in",
        "career_url": "https://dbtindia.gov.in/latest-announcement/vacancies",
        "recruitment_url": "https://dbtindia.gov.in/latest-announcement/vacancies",
        "source_type": "portal",
    },
    {
        "organisation_name": "Ministry of Education (MoE)",
        "organisation_type": "ministry",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "education.gov.in",
        "career_url": "https://www.education.gov.in/vacancies",
        "recruitment_url": "https://www.education.gov.in/vacancies",
        "source_type": "portal",
    },
    {
        "organisation_name": "Ministry of Health and Family Welfare (MoHFW)",
        "organisation_type": "ministry",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "mohfw.gov.in",
        "career_url": "https://www.mohfw.gov.in/vacancies",
        "recruitment_url": "https://www.mohfw.gov.in/vacancies",
        "source_type": "portal",
    },
    {
        "organisation_name": "National Informatics Centre (NIC)",
        "organisation_type": "attached_office",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "nic.in",
        "career_url": "https://www.nic.in/recruitment",
        "recruitment_url": "https://recruitment.nic.in",
        "source_type": "portal",
    },
    {
        "organisation_name": "Digital India Corporation (DIC)",
        "organisation_type": "statutory_body",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "dic.gov.in",
        "career_url": "https://dic.gov.in/index.php/vacancies",
        "recruitment_url": "https://dic.gov.in/index.php/vacancies",
        "source_type": "portal",
    },
    {
        "organisation_name": "National e-Governance Division (NeGD)",
        "organisation_type": "mission",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "negd.gov.in",
        "career_url": "https://negd.gov.in/careers",
        "recruitment_url": "https://negd.gov.in/careers",
        "source_type": "portal",
    },
    {
        "organisation_name": "IndiaAI Mission",
        "organisation_type": "mission",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "indiaai.gov.in",
        "career_url": "https://indiaai.gov.in/opportunities",
        "recruitment_url": "https://indiaai.gov.in/opportunities",
        "source_type": "portal",
    },

    # --- AUTONOMOUS BODIES & PSUs ---
    {
        "organisation_name": "Centre for Development of Advanced Computing (C-DAC)",
        "organisation_type": "psu",
        "government_level": "central",
        "state": "Maharashtra",
        "city": "Pune",
        "official_domain": "cdac.in",
        "career_url": "https://www.cdac.in/index.aspx?id=careers",
        "recruitment_url": "https://www.cdac.in/index.aspx?id=careers",
        "source_type": "portal",
    },
    {
        "organisation_name": "National Institute of Electronics and Information Technology (NIELIT)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "nielit.gov.in",
        "career_url": "https://www.nielit.gov.in/recruitments",
        "recruitment_url": "https://www.nielit.gov.in/recruitments",
        "source_type": "portal",
    },
    {
        "organisation_name": "Software Technology Parks of India (STPI)",
        "organisation_type": "autonomous_body",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "stpi.in",
        "career_url": "https://www.stpi.in/en/careers",
        "recruitment_url": "https://www.stpi.in/en/careers",
        "source_type": "portal",
    },
    {
        "organisation_name": "Bharat Electronics Limited (BEL)",
        "organisation_type": "psu",
        "government_level": "central",
        "state": "Karnataka",
        "city": "Bengaluru",
        "official_domain": "bel-india.in",
        "career_url": "https://bel-india.in/careers/",
        "recruitment_url": "https://bel-india.in/careers/",
        "source_type": "portal",
    },
    {
        "organisation_name": "Unique Identification Authority of India (UIDAI)",
        "organisation_type": "statutory_body",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "uidai.gov.in",
        "career_url": "https://uidai.gov.in/en/about-uidai/work-with-uidai.html",
        "recruitment_url": "https://uidai.gov.in/en/about-uidai/work-with-uidai.html",
        "source_type": "portal",
    },
    {
        "organisation_name": "Telecom Regulatory Authority of India (TRAI)",
        "organisation_type": "regulator",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "trai.gov.in",
        "career_url": "https://www.trai.gov.in/notifications/vacancies",
        "recruitment_url": "https://www.trai.gov.in/notifications/vacancies",
        "source_type": "portal",
    },

    # --- RESEARCH & HIGHER EDUCATION ---
    {
        "organisation_name": "Council of Scientific and Industrial Research (CSIR)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "csir.res.in",
        "career_url": "https://www.csir.res.in/career-opportunities/recruitment",
        "recruitment_url": "https://www.csir.res.in/career-opportunities/recruitment",
        "source_type": "portal",
    },
    {
        "organisation_name": "Indian Council of Medical Research (ICMR)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "icmr.nic.in",
        "career_url": "https://main.icmr.nic.in/career-opportunity",
        "recruitment_url": "https://main.icmr.nic.in/career-opportunity",
        "source_type": "portal",
    },
    {
        "organisation_name": "Defence Research and Development Organisation (DRDO)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "drdo.gov.in",
        "career_url": "https://www.drdo.gov.in/careers",
        "recruitment_url": "https://www.drdo.gov.in/careers",
        "source_type": "portal",
    },
    {
        "organisation_name": "Indian Space Research Organisation (ISRO)",
        "organisation_type": "research_institute",
        "government_level": "central",
        "state": "Karnataka",
        "city": "Bengaluru",
        "official_domain": "isro.gov.in",
        "career_url": "https://www.isro.gov.in/Careers.html",
        "recruitment_url": "https://www.isro.gov.in/Careers.html",
        "source_type": "portal",
    },
    {
        "organisation_name": "Indian Institute of Science (IISc Bengaluru)",
        "organisation_type": "university",
        "government_level": "central",
        "state": "Karnataka",
        "city": "Bengaluru",
        "official_domain": "iisc.ac.in",
        "career_url": "https://iisc.ac.in/positions-open/",
        "recruitment_url": "https://iisc.ac.in/positions-open/",
        "source_type": "portal",
    },
    {
        "organisation_name": "Indian Institute of Technology Delhi (IIT Delhi)",
        "organisation_type": "university",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "iitd.ac.in",
        "career_url": "https://home.iitd.ac.in/jobs-iitd.php",
        "recruitment_url": "https://home.iitd.ac.in/jobs-iitd.php",
        "source_type": "portal",
    },
    {
        "organisation_name": "Indian Institute of Technology Kanpur (IIT Kanpur)",
        "organisation_type": "university",
        "government_level": "central",
        "state": "Uttar Pradesh",
        "city": "Kanpur",
        "official_domain": "iitk.ac.in",
        "career_url": "https://www.iitk.ac.in/new/recruitment",
        "recruitment_url": "https://www.iitk.ac.in/dord/project-appointments",
        "source_type": "portal",
    },
    {
        "organisation_name": "Indian Institute of Technology Bombay (IIT Bombay)",
        "organisation_type": "university",
        "government_level": "central",
        "state": "Maharashtra",
        "city": "Mumbai",
        "official_domain": "iitb.ac.in",
        "career_url": "https://www.iitb.ac.in/en/careers",
        "recruitment_url": "https://www.ircc.iitb.ac.in/IRCC-Web/JobOpportunities.jsp",
        "source_type": "portal",
    },
    {
        "organisation_name": "Indian Institute of Technology Madras (IIT Madras)",
        "organisation_type": "university",
        "government_level": "central",
        "state": "Tamil Nadu",
        "city": "Chennai",
        "official_domain": "iitm.ac.in",
        "career_url": "https://www.iitm.ac.in/careers",
        "recruitment_url": "https://icandsr.iitm.ac.in/recruitment/",
        "source_type": "portal",
    },

    # --- HEALTHCARE INSTITUTIONS ---
    {
        "organisation_name": "All India Institute of Medical Sciences (AIIMS New Delhi)",
        "organisation_type": "hospital",
        "government_level": "central",
        "state": "Delhi",
        "city": "New Delhi",
        "official_domain": "aiims.edu",
        "career_url": "https://www.aiims.edu/en/notices/recruitment.html",
        "recruitment_url": "https://www.aiims.edu/en/notices/recruitment.html",
        "source_type": "portal",
    },

    # --- STATE GOVERNMENTS (REPRESENTATIVE SEEDS FOR COVERAGE EXPANSION) ---
    {
        "organisation_name": "Government of Uttar Pradesh (UP Portal)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Uttar Pradesh",
        "city": "Lucknow",
        "official_domain": "up.gov.in",
        "career_url": "https://rojgaarsangam.up.gov.in",
        "recruitment_url": "https://up.gov.in/en/page/recruitment",
        "source_type": "portal",
    },
    {
        "organisation_name": "Uttar Pradesh State Disaster Management Authority (UPSDMA)",
        "organisation_type": "authority",
        "government_level": "state",
        "state": "Uttar Pradesh",
        "city": "Lucknow",
        "official_domain": "upsdma.up.nic.in",
        "career_url": "http://upsdma.up.nic.in/Recruitment.aspx",
        "recruitment_url": "http://upsdma.up.nic.in/Recruitment.aspx",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Maharashtra",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Maharashtra",
        "city": "Mumbai",
        "official_domain": "maharashtra.gov.in",
        "career_url": "https://maharecruitment.mahaonline.gov.in",
        "recruitment_url": "https://www.maharashtra.gov.in",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Karnataka (e-Governance Department)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Karnataka",
        "city": "Bengaluru",
        "official_domain": "karnataka.gov.in",
        "career_url": "https://dpar.karnataka.gov.in",
        "recruitment_url": "https://karnataka.gov.in/page/Recruitments/en",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Kerala (Information Technology Mission)",
        "organisation_type": "mission",
        "government_level": "state",
        "state": "Kerala",
        "city": "Thiruvananthapuram",
        "official_domain": "itmission.kerala.gov.in",
        "career_url": "https://itmission.kerala.gov.in/careers",
        "recruitment_url": "https://itmission.kerala.gov.in/careers",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Tamil Nadu",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Tamil Nadu",
        "city": "Chennai",
        "official_domain": "tn.gov.in",
        "career_url": "https://www.tn.gov.in/employment",
        "recruitment_url": "https://www.tn.gov.in/announcements",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Gujarat (Science & Technology)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Gujarat",
        "city": "Gandhinagar",
        "official_domain": "dst.gujarat.gov.in",
        "career_url": "https://dst.gujarat.gov.in/recruitment.htm",
        "recruitment_url": "https://dst.gujarat.gov.in/recruitment.htm",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Rajasthan (DoIT&C)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Rajasthan",
        "city": "Jaipur",
        "official_domain": "doitc.rajasthan.gov.in",
        "career_url": "https://doitc.rajasthan.gov.in/pages/recruitments",
        "recruitment_url": "https://doitc.rajasthan.gov.in/pages/recruitments",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of West Bengal",
        "organisation_type": "department",
        "government_level": "state",
        "state": "West Bengal",
        "city": "Kolkata",
        "official_domain": "wb.gov.in",
        "career_url": "https://wb.gov.in/portal/web/guest/recruitment",
        "recruitment_url": "https://wb.gov.in/portal/web/guest/recruitment",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Madhya Pradesh (MAP_IT)",
        "organisation_type": "autonomous_body",
        "government_level": "state",
        "state": "Madhya Pradesh",
        "city": "Bhopal",
        "official_domain": "mapit.gov.in",
        "career_url": "https://mapit.gov.in/career.aspx",
        "recruitment_url": "https://mapit.gov.in/career.aspx",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Telangana (ITE&C)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Telangana",
        "city": "Hyderabad",
        "official_domain": "it.telangana.gov.in",
        "career_url": "https://it.telangana.gov.in/careers/",
        "recruitment_url": "https://it.telangana.gov.in/careers/",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Andhra Pradesh (ITE&C)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Andhra Pradesh",
        "city": "Vijayawada",
        "official_domain": "it.ap.gov.in",
        "career_url": "https://it.ap.gov.in/careers",
        "recruitment_url": "https://it.ap.gov.in/careers",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Odisha (Electronics & IT)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Odisha",
        "city": "Bhubaneswar",
        "official_domain": "eandit.odisha.gov.in",
        "career_url": "https://eandit.odisha.gov.in/recruitments",
        "recruitment_url": "https://eandit.odisha.gov.in/recruitments",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Punjab (DGRPG)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Punjab",
        "city": "Chandigarh",
        "official_domain": "dgrpg.punjab.gov.in",
        "career_url": "https://dgrpg.punjab.gov.in/recruitments/",
        "recruitment_url": "https://dgrpg.punjab.gov.in/recruitments/",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Haryana (DITECH)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Haryana",
        "city": "Chandigarh",
        "official_domain": "ditech.haryana.gov.in",
        "career_url": "https://ditech.haryana.gov.in/recruitment",
        "recruitment_url": "https://ditech.haryana.gov.in/recruitment",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Bihar (Beltron / IT Dept)",
        "organisation_type": "psu",
        "government_level": "state",
        "state": "Bihar",
        "city": "Patna",
        "official_domain": "bsedc.bihar.gov.in",
        "career_url": "https://bsedc.bihar.gov.in/en/recruitment",
        "recruitment_url": "https://bsedc.bihar.gov.in/en/recruitment",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Assam (IT Dept)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Assam",
        "city": "Guwahati",
        "official_domain": "it.assam.gov.in",
        "career_url": "https://it.assam.gov.in/portlets/recruitment",
        "recruitment_url": "https://it.assam.gov.in/portlets/recruitment",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Himachal Pradesh (DIT)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Himachal Pradesh",
        "city": "Shimla",
        "official_domain": "himachal.nic.in",
        "career_url": "https://himachal.nic.in/en-IN/vacancies.html",
        "recruitment_url": "https://himachal.nic.in/en-IN/vacancies.html",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Uttarakhand (ITDA)",
        "organisation_type": "authority",
        "government_level": "state",
        "state": "Uttarakhand",
        "city": "Dehradun",
        "official_domain": "itda.uk.gov.in",
        "career_url": "https://itda.uk.gov.in/recruitment",
        "recruitment_url": "https://itda.uk.gov.in/recruitment",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Goa (DITEG)",
        "organisation_type": "department",
        "government_level": "state",
        "state": "Goa",
        "city": "Panaji",
        "official_domain": "ditc.goa.gov.in",
        "career_url": "https://ditc.goa.gov.in/recruitment",
        "recruitment_url": "https://ditc.goa.gov.in/recruitment",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Chhattisgarh (CHIPS)",
        "organisation_type": "society",
        "government_level": "state",
        "state": "Chhattisgarh",
        "city": "Raipur",
        "official_domain": "chips.gov.in",
        "career_url": "https://chips.gov.in/en/careers",
        "recruitment_url": "https://chips.gov.in/en/careers",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Jharkhand (JAP-IT)",
        "organisation_type": "society",
        "government_level": "state",
        "state": "Jharkhand",
        "city": "Ranchi",
        "official_domain": "japit.jharkhand.gov.in",
        "career_url": "https://japit.jharkhand.gov.in/recruitment.aspx",
        "recruitment_url": "https://japit.jharkhand.gov.in/recruitment.aspx",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of Jammu and Kashmir",
        "organisation_type": "department",
        "government_level": "ut",
        "state": "Jammu and Kashmir",
        "city": "Srinagar",
        "official_domain": "jkit.nic.in",
        "career_url": "https://jkit.nic.in/recruitment.html",
        "recruitment_url": "https://jkit.nic.in/recruitment.html",
        "source_type": "portal",
    },
    {
        "organisation_name": "Administration of Ladakh",
        "organisation_type": "department",
        "government_level": "ut",
        "state": "Ladakh",
        "city": "Leh",
        "official_domain": "ladakh.gov.in",
        "career_url": "https://ladakh.gov.in/advertisement-and-notices/",
        "recruitment_url": "https://ladakh.gov.in/advertisement-and-notices/",
        "source_type": "portal",
    },
    {
        "organisation_name": "Administration of Andaman and Nicobar Islands",
        "organisation_type": "department",
        "government_level": "ut",
        "state": "Andaman and Nicobar Islands",
        "city": "Port Blair",
        "official_domain": "andaman.gov.in",
        "career_url": "https://erecruitment.andaman.gov.in/",
        "recruitment_url": "https://erecruitment.andaman.gov.in/",
        "source_type": "portal",
    },
    {
        "organisation_name": "Government of NCT of Delhi",
        "organisation_type": "department",
        "government_level": "ut",
        "state": "Delhi",
        "city": "Delhi",
        "official_domain": "delhi.gov.in",
        "career_url": "https://delhi.gov.in/vacancies",
        "recruitment_url": "https://delhi.gov.in/vacancies",
        "source_type": "portal",
    },
]

SEED_SOURCES = SEED_GOVERNMENT_ORGANISATIONS
